### ISSUE TITLE
Error while writing the test

### ISSUE THREAD

**Issue by inguldima** [spatie/laravel-data#241]
If I use DataObject in Unit Test, I Have this error
`Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #0 [ <required> array $config ]] in class Spatie\LaravelData\Support\DataConfig
`

**Comment by rubenvanassche** [comment]
Somehow the LaravelDtaaServiceProvider isn't ran: https://github.com/spatie/laravel-data/blob/main/src/LaravelDataServiceProvider.php

Make sure it is otherwise the required bindings are not set up.

**Comment by nickbeen** [comment]
@inguldima You need to use feature tests, the service provider isn't bound because of the different TestCase class used in unit tests.

```php
//use PHPUnit\Framework\TestCase;
use Tests\TestCase;
```

**Comment by trianity** [comment]
I ran into a similar problem.
The spatie/laravel-data package was used in my own package with Pest 2.x test framework.

The error message is: **BindingResolutionException Unresolvable dependency resolving [Parameter #0 [ <required> array $config ]] in class Spatie\LaravelData\Support\DataConfig**

My PackageTestCase was used as follow:

```
use Orchestra\Testbench\TestCase;

class PackageTestCase extends TestCase
{
}
```
Any idea to correct?
