### ISSUE TITLE
Case mappers don't work as (presumably) intended.

### ISSUE THREAD

**Issue by mathmul** [spatie/laravel-data#242]
Using Win 11 / WSL 2 (Ubuntu) / PHP 8.1.12.

### Test usage:
```php
$tmp = json_decode($employeesJson, true)[0];
$data = Employee::from($tmp);
rd($tmp, $data);
```
### 👍 works
```php
use Spatie\LaravelData\Attributes\MapInputName;
use Spatie\LaravelData\Data;

class EmployeeData extends Data
{
    public function __construct(
        #[MapInputName('Id')]                   public ?int $id = null,
        #[MapInputName('ReferenceId')]          public ?string $referenceId = null,
        #[MapInputName('OrganizationalUnitId')] public ?int $organizationalUnitId = null,
        #[MapInputName('Active')]               public ?bool $active = null,
    ) { }
}
/* Ray output
array:32 [▼
  "Id" => 69
  "ReferenceId" => "552"
  "OrganizationalUnitId" => 123011821
  "Active" => true
]
App\Data\EmployeeData {#3342 ▼
  +id: 69
  +referenceId: "552"
  +organizationalUnitId: 123011821
  +active: true
}
*/
```
### 👎doesn't
```php
use Spatie\LaravelData\Attributes\MapInputName;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Mappers\CamelCaseMapper;

#[MapInputName(CamelCaseMapper::class)]
class EmployeeData extends Data
{
    public function __construct(
        public ?int $id = null,
        public ?string $referenceId = null,
        public ?int $organizationUnitId = null,
        public ?bool $active = null,
    ) { }
}
/* Ray output
array:32 [▼
  "Id" => 69
  "ReferenceId" => "552"
  "OrganizationalUnitId" => 123011821
  "Active" => true
]
App\Data\EmployeeData {#3342 ▼
  +id: null
  +referenceId: null
  +organizationalUnitId: null
  +active: null
}
*/
```
Perhaps I just misunderstood the intended usage or something...

**Comment by Nir-An** [comment]
Hi @mathmul 

In the first example, you force exactly the name for the input name  (with the capital letter at the first of the key)

in the second example, you  force the input name to be camelCase (without a capital letter at the first of the key.)
so the keys should be 
id ,
referenceId,
organizationalUnitId,
active

**Comment by mathmul** [comment]
Thank you @Nir-An for replying. I gratefully accept the answer, and acknowledge @rubenvanassche  closing the issue is justified.

That said, could we have a small discussion about it, to help me clarify what's going on?

To me, the usage in the first example is totally intuitive. First we say what the input is exactly (`'Id'`) and then which property we map it to (`$id`).

The usage in the second example is less obvious to this dummy. The way I see it, it should work like "Accept input in any case, convert it to camelCase, and assign it's value to a property of same name (possibly only if it exits, without error otherwise)". But if I understand you correctly, it means just the opposite ie. "Accept input only in camelCase, and assign it's value a property of same name (...)". This baffles me, because it feels more like a rule, rather than a mapping.

Accepting your explanation, I then went and copied CamelCaseMapper class, renamed to StudlyCapsMapper and changed the last return line to `Str::studly($name)`. Trying the second example again, but with `#[MapInputName(StudlyCapsMapper::class)]` instead, failed again, though I didn't (nor do I want to) capitalize the four properties.

Could you please offer a 1:1 example on how to refactor the code in the first example to work without explicitly mapping each property?

**Comment by Nir-An** [comment]
hello @mathmul 
your question is fine and legitimate, in general, you can always ask in the [discussion tab](https://github.com/spatie/laravel-data/discussions)

map input name is optional.
 
you can try  [Magical creation](https://spatie.be/docs/laravel-data/v2/as-a-data-transfer-object/creating-a-data-object#content-magical-creation) to convert data to object 

According to your example, it should look like this: 

```php

    public static function fromArray(Array $employee): self
    {

        public function __construct(
            public ?int $id = null,
            public ?string $referenceId = null,
            public ?int $organizationUnitId = null,
            public ?bool $active = null,
    ) { }


        return new self(
             id:$employee['Id'],
             referenceId:$employee['ReferenceId'],
             organizationalUnitId:$employee['OrganizationalUnitId'],
             active:$employee['Active'],
         );
    }
```

**Comment by mathmul** [comment]
Hi @Nir-An 

Thanks, but you still have to type out PascalCased names in your example, just elsewhere. If that can't be avoided, then so be it. I'll stick to my first example. Appreciate the effort!

**Comment by Nir-An** [comment]
> Hi @Nir-An
> 
> Thanks, but you still have to type out PascalCased names in your example, just elsewhere. If that can't be avoided, then so be it. I'll stick to my first example. Appreciate the effort!

I understand your point but this package can't be responsible for the data that came from the JSON 

in Megicla creation way only the spsific type should convert from StudlyCaps (in your example we talking about array type) 
in your first example, all types should be StudlyCaps including models!! to create a data object

**Comment by rubenvanassche** [comment]
Hi @mathmul,

I get that the mappers are a bit confusing, they need to work both for input and output. In this case they will be used to map your data property names onto your payload property names. I've made the docs a bit more clear on that. Secondly I've added a StudlyMapper which should be useful in your case.

If I run this test: 

```php

    #[MapInputName(StudlyCaseMapper::class)]
    class EmployeeData extends Data
    {
        public function __construct(
            public ?int $id = null,
            public ?string $referenceId = null,
            public ?int $organizationalUnitId = null,
            public ?bool $active = null,
        ) {
        }
    }

    $c = EmployeeData::from([
        "Id" => 69,
        "ReferenceId" => "552",
        "OrganizationalUnitId" => 123011821,
        "Active" => true,
    ]);

    dd($c);
```

I get: 

```
EmployeeData {#2756 // /Users/ruben/Spatie/laravel-data-resource/tests/DataTest.php:2287
  +id: 69
  +referenceId: "552"
  +organizationalUnitId: 123011821
  +active: true
}
```

See ae0dc438fef9859a0ed9eb1e643c123ee9b6b296

**Comment by rubenvanassche** [comment]
And thans @Nir-An for the excellent answers as always!
