### ISSUE TITLE
Freeze when using recursive data annotations

### ISSUE THREAD

**Issue by Azeirah** [spatie/laravel-data#251]
I'm using a structure akin to, my code is of course a bit more involved but this is the basic idea

```php
class Item extends Data {
  public function __construct(
    public int $item_id,
    public int $quantity,
    #[DataCollectionOf(Item::class)]
    public ?DataCollection $subItems) {}
}
```

As you can see, my Item optionally nests a collection of Items, but this freezes. The request simply times out.

Is it possible there's an accidental infinite loop in the code due to this annotation?

**Comment by jhorie** [comment]
```php
class Item extends Data {
  public function __construct(
    public int $item_id,
    public int $quantity,
    public ?Item $subItem) {}
}
```

This is also giving the same timeout. Looks like nesting same class gives you a timeout.

**Comment by rubenvanassche** [comment]
This is impossible because we cannot know how deep we should generate validation rules, I've added a section in the docs describing it: https://github.com/spatie/laravel-data/blob/b8a0efd9263fbff1da2466bdca9e50e346ba6e44/docs/as-a-data-transfer-object/request-to-data-object.md#L575

**Comment by DiederikvandenB** [comment]
@rubenvanassche is this also impossible for a many to many relationship? I have an `InvoiceData` class which has a `DataCollectionOf(TransactionData::class)`, and the `TransactionData` class also has a `DataCollectionOf(InvoiceData::class)`. Currently, I get a timeout/memory leak when I run `InvoiceData::getValidationRules();`

**Comment by rubenvanassche** [comment]
Yeah it is a circular loop, something validation rules generation doesn't like 😄
