### ISSUE TITLE
Incorrect `$payload` content in parameters of `rule` method 

### ISSUE THREAD

**Issue by medvinator** [spatie/laravel-data#256]
Structure

```php
class ArtistData extends Data
{
    public function __construct(
        public string $name,
        public int $age,
    ) {
    }
}

class AlbumData extends Data
{
    public function __construct(
        public string $title,
        public ArtistData $artist,
    ) {
    }
}
```

There is a need to build rules depending on the payload in ArtistData.
It's easy according to the docs.

```php
    public static function rules(array $payload): array
    {
        ray($payload);
        return [];
    }
```

I thought this payload is relative to the data class, but no 🦊

Suppose I have 2 endpoints: create an artist and create an album.
In both cases, this payload will be different and will actually repeat the request body.

In case **create an album** it will be
```php
[
  "title" => "title"
  "artist" => [
    "name" => "name"
    "age" => 20
  ]
]
```

But ArtistData doesn't know what key is used in AlbumData.

Is this correct behavior or is something wrong?

**Comment by rubenvanassche** [comment]
I'm aware this happens, it is kinda in line with the Laravel custom validation rules which also always will get a full payload, even when they are nested.

That being said, I would love a more related payload in these methods but haven't got the time right now to built such thing. I would certainly merge a well tested (which is quite important here) PR adding this functionality.
