### ISSUE TITLE
Error Deploying to Heroku

### ISSUE THREAD

**Issue by kxgcayh** [spatie/laravel-data#259]
![HerokuError](https://user-images.githubusercontent.com/48075412/202825883-ba8bfd1a-d712-438e-959c-087eb43d69c9.png)

My Application running wel in local, but it return Error from LaravelData\Support\DataConfig

**Comment by Wulfheart** [comment]
Did you update your composer dependencies on Heroku?

**Comment by Nir-An** [comment]
Further to what Wulfheart wrote
Please make sure:
1. ``config/data.php`` was created 
2. clear the cache

**Comment by rubenvanassche** [comment]
This looks like the correct solution, I'm gonna close this. 

Errors like

> Unresolvable dependency resolving [Parameter #0 [ «required> array $config il in class
Spatie\LaravelData\Support\DataConfig

Always indicate the `SettingsServiceProvider` didn't run.
