### ISSUE TITLE
Memory Leak / Infinite Loop when trying to validate or getValidationRules

### ISSUE THREAD

**Issue by goellner** [spatie/laravel-data#321]
Just hit a bug where Laravel throws runs out of memory when trying to do something like User::validate($array) or even User::getValidationRules(). 

```
Symfony\Component\ErrorHandler\Error\FatalError 

  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 57344 bytes)

  at vendor/spatie/laravel-data/src/Resolvers/DataPropertyValidationRulesResolver.php:154
   ```
  
  I found that if a DTO has relations configured that have circular dependencies, it runs out of memory:
  
  e.g.
  Models:
  User 
  Recipe
  
  Relations:
  A user has many recipes
  A recipe belongs to a user
  
  When I comment out the following lines on the User DTO it works:
  
  ```
  public function __construct(
        #[DataCollectionOf(RecipeData::class)]
        public readonly Optional|Lazy|DataCollection $recipes,
){}
```

**Comment by rubenvanassche** [comment]
This is described within the docs: https://spatie.be/docs/laravel-data/v2/as-a-data-transfer-object/request-to-data-object#content-validation-and-nesting-or-collecting-the-same-class
