### ISSUE TITLE
DataCollectionOf cast ignores global custom cast

### ISSUE THREAD

**Issue by pr4xx** [spatie/laravel-data#330]
Hey there, I am encountering an issue when using the `DataCollectionOf` attribute together with an abstract class and custom cast.

Basically the attribute is used like this:
```php
#[DataCollectionOf(MessageContent::class)]
```

Whereas `MessageContent` is an abstract class. A custom cast takes care of creating the correct concrete object. This works as long as I typehint a single instance:

```php
public MessageContent $content
```

But now I have a collection of these `MessageContent` objects. Basically the attribute is used like this:
```php
#[DataCollectionOf(MessageContent::class)]
public DataCollection $contents
```

Now I get the following error:

```
Error: Cannot instantiate abstract class Namespace\MessageContent in file /path/vendor/spatie/laravel-data/src/Resolvers/DataFromArrayResolver.php on line 60
```

My guess is that the `DataFromArrayResolver` somehow ignores the custom cast config in `data.php`.

**Comment by rubenvanassche** [comment]
Could you provide me a more in depth code example? It is not completely clear for me how these objects are all related to each other.

Also, it is at this point in time not possible to have multiple types of data classes within one DataCollection, some parts of the package will probably work but others fail completely.

**Comment by pr4xx** [comment]
> Also, it is at this point in time not possible to have multiple types of data classes within one DataCollection

Even if all data classes inherit from the same base class, such as `MessageContent` in my case?

**Comment by pr4xx** [comment]
Alright, then I should close this issue for now. Thanks!
