### ISSUE TITLE
except only methods not working with Laravel jobs

### ISSUE THREAD

**Issue by firefoxuz** [spatie/laravel-data#359]
`                $courierReportData->except('courier_number');
                $courierReportData->toJson();`
I am trying except one propetry from all data but it returns all properties when using insde laravel job

**Comment by rubenvanassche** [comment]
When serializing a data object all includes, excludes, only and excepts are thrown away to keep the serialized version of your object clean. You probably should add your excepts to your job's constructor to make this work.
