### ISSUE TITLE
Unexpected behaviour when using `fromRequest` magic method

### ISSUE THREAD

**Issue by joshdcuneo** [spatie/laravel-data#361]
Hi there, let me start by saying thanks for all the great php libraries from Spatie!

I ran into something unexpected when trying to validate requests using laravel-data. In particular when trying to set defaults for non-nullable properties in the `static fromRequest` method.

I've added a test case to reproduce the behaviour to a [fork](https://github.com/spatie/laravel-data/compare/main...joshdcuneo:laravel-data:main).

It appears that perhaps validation is run on the Laravel request before the data object is constructed? It may be that this is the intended behaviour and I just missed that in the documentation? I guess my expectation looking at the api of the library was that the validation would be run against the constructed data object.

**Comment by rubenvanassche** [comment]
> It appears that perhaps validation is run on the Laravel request before the data object is constructed?

That's correct, since if we would run validation after object creation you could possibly construct an object with wrong types which would throw PHP errors you don't want to deal with when creating a validated data object.

I've added an extra sentence to the docs about this describing this.

**Comment by joshdcuneo** [comment]
Thanks for clarifying, that makes perfect sense.

On March 2, 2023, Steve Smith ***@***.***> wrote:
> > It appears that perhaps validation is run on the Laravel request
> > before the data object is constructed?
> >
>
> That's correct, since if we would run validation after object creation
> you could possibly construct an object with wrong types which would
> throw PHP errors you don't want to deal with when creating a validated
> data object.
>
> I've added an extra sentence to the docs about this describing this.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/spatie/laravel-data/issues/361#issuecomment-
1451663686>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AI2S4UZNLWED24ZRZYOQOPTW2B27LANCNFSM6AAAAAAVII6QGM>.
You are receiving this because you authored the thread.Message ID:
***@***.***>
