### ISSUE TITLE
Local Casts for Spatie Laravel Enum in Data Object isn't working

### ISSUE THREAD

**Issue by Lawebso** [spatie/laravel-data#363]
Hello,

I can't get the enum casting example to work when creating a data object from an array

I'm using the following versions

Laravel 10
"spatie/laravel-data": "^3.1.0",
"spatie/laravel-enum": "^3.0.2",

First I want to mention that I also tried the exact example as presented in the docs: 
https://spatie.be/docs/laravel-data/v3/as-a-data-transfer-object/casts

I got the same error.

I create a data object like this:
<img width="612" alt="Screenshot 2023-03-01 at 12 03 01 PM" src="https://user-images.githubusercontent.com/106002156/222042659-59f2b73c-6656-4b6c-8a56-56f9215c1443.png">

My Enum looks like this:
<img width="481" alt="Screenshot 2023-03-01 at 12 02 37 PM" src="https://user-images.githubusercontent.com/106002156/222042692-c157f561-0eb4-4071-b718-468a913f8b4d.png">

Now I'm trying to create a data object from an array like so:
<img width="348" alt="Screenshot 2023-03-01 at 12 03 13 PM" src="https://user-images.githubusercontent.com/106002156/222042763-3589d234-365a-4990-9af7-39bae15ea259.png">

Unfortunately I get the following error:
<img width="987" alt="Screenshot 2023-03-01 at 12 03 30 PM" src="https://user-images.githubusercontent.com/106002156/222042815-fdd4d6ee-54d6-4a5f-b7d0-84335b8ecbd8.png">

What am I missing here? Like mentioned above I also tried the exact example from the docs and I get the same error.

**Comment by rubenvanassche** [comment]
The package doesn't have a cast (anymore) for the spatie enum package, the cast you're using is for native PHP casts. You will have to implement your own cast if you want to use spatie enums.

**Comment by faizalmy** [comment]
![image](https://user-images.githubusercontent.com/1636216/222923755-4222b756-cc6c-4012-945a-a65919dd3474.png)
![image](https://user-images.githubusercontent.com/1636216/222923770-3bb6026e-0a9f-4265-a532-6eddcda4a362.png)

I'm experiencing a similar issue even though I'm using my own cast class and have followed the documentation. Can you suggest what I might be overlooking?

**Comment by faizalmy** [comment]
solved. need to include this.

`use Spatie\LaravelData\Attributes\WithCast;`
