### ISSUE TITLE
Only, except, include, exclude in a query string ignores MapOutputName and MapName (CaseMapper)

### ISSUE THREAD

**Issue by mlshvdv** [spatie/laravel-data#387]
## Description

> (!) The following model, data object, and controller are only simplified to demonstrate the problem.

There is a simple eloquent model:

```php
<?php
declare(strict_types=1);

namespace Billing\Models;

use App\Models\BaseModel;
use Billing\DataObjects\InvoiceDataObject;

class Invoice extends BaseModel
{
    protected string $dataClass = InvoiceDataObject::class;

    protected $table = 'invoices';

    protected $dates = [
        'expires_at'
    ];

    protected $fillable = [
        'id',
        'paid_amount',
        'expires_at',
    ];

}
```

Data object:

```php
<?php
declare(strict_types=1);

namespace Billing\DataObjects;

#[MapName(SnakeCaseMapper::class)]
class InvoiceDataObject extends DataObject
{
    public function __construct(
        public Optional|Lazy|string $id,
        public Optional|Lazy|string $paidAmount,
        #[MapOutputName('due_at')]
        #[WithCast(DateTimeInterfaceCast::class)]
        public Optional|Lazy|\DateTime $expiresAt
    )
    { 
    }

    public static function allowedRequestIncludes(): ?array
    {
        return [
            'id',
            'paidAmount',
            'expiresAt'
        ];
    }

    public static function allowedRequestOnly(): ?array
    {
        return [
            'id',
            'paidAmount',
            'expiresAt'
        ];
    }

    public static function allowedRequestExcept(): ?array
    {
        return [
            'id',
            'paidAmount',
            'expiresAt'
        ];
    }

    public static function allowedRequestExcludes(): ?array
    {
        return [
            'id',
            'paidAmount',
            'expiresAt'
        ];
    }

    public function includeProperties(): array
    {
        return [
            'id'                    => true,
            'paidAmount'  => true,
            'expiresAt'       => true,
        ];
    }

    public static function fromModel(Invoice $record): self
    {
        $data = $record->toArray();
        $lazyModel = [];
        foreach ($data as $key => $value) {
           $lazyModel[$key] = Lazy::create(fn() => $value);
        }

        return self::from(
            [
                ...$lazyModel
            ]
        );
    }
}
```

And simple controller:
```php
<?php
declare(strict_types=1);

namespace Billing\V1\Http\Controllers;

use App\Http\Controllers\Controller;
use Billing\Models\Invoice;
use Billing\V1\Http\Requests\InvoiceGetRequest;

class InvoiceController extends Controller
{
    /**
     * Return invoice
     *
     * @param InvoiceGetRequest $request
     * @param Invoice $invoice
     */
    public function get(InvoiceGetRequest $request, Invoice $invoice)
    {
        return $invoice->getData()->toResponse($request);
    }
}
```

The base response for this action looks like this:
```json
{
    "id": "a502674e-3f74-4d73-a839-cdfcfcf76fed",
    "paid_amount": "0.00",
    "due_at": "2023-02-09T18:21:54.753084Z"
}
```

## Case 1: Case Mapper ignoring (`#[MapName(SnakeCaseMapper::class)]`)

Ok. Let's try to make the request to this action using query string params:
```
GET https://.../v1/billing/invoices/a502674e-3f74-4d73-a839-cdfcfcf76fed?except=paid_amount
```

The response **still contains** `paid_amount`:
```json
{
    "id": "a502674e-3f74-4d73-a839-cdfcfcf76fed",
    "paid_amount": "0.00",
    "due_at": "2023-02-09T18:21:54.753084Z"
}
```

Ok, let's try to repeat the request but with `?except=paidAmount`:
```
GET https://.../v1/billing/invoices/a502674e-3f74-4d73-a839-cdfcfcf76fed?except=paidAmount
```

The response **will be without** `paid_amount`:
```json
{
    "id": "a502674e-3f74-4d73-a839-cdfcfcf76fed",
    "due_at": "2023-02-09T18:21:54.753084Z"
}
```

It seems that when using CaseMapper, filtering by query string does not take into account the actual mapping.

## Case 2: MapOutputName ignoring (`#[MapOutputName('due_at')]`)

Let's try to make the request to this action using query string params:
```
GET https://.../v1/billing/invoices/a502674e-3f74-4d73-a839-cdfcfcf76fed?except=due_at
```

The response **still contains** `due_at`:
```json
{
    "id": "a502674e-3f74-4d73-a839-cdfcfcf76fed",
    "paid_amount": "0.00",
    "due_at": "2023-02-09T18:21:54.753084Z"
}
```

Let's continue using the query with `?except=dueAt`:
```
GET https://.../v1/billing/invoices/a502674e-3f74-4d73-a839-cdfcfcf76fed?except=dueAt
```

The response **still contains** `due_at`:
```json
{
    "id": "a502674e-3f74-4d73-a839-cdfcfcf76fed",
    "paid_amount": "0.00",
    "due_at": "2023-02-09T18:21:54.753084Z"
}
```

It seems, that it's necessary to say to the mobile app developer, that `due_at is equal to expires_at` and he must use `?except=expiresAt` in the query. Looks strange, but it works:

```
GET https://.../v1/billing/invoices/a502674e-3f74-4d73-a839-cdfcfcf76fed?except=expiresAt
```

Now no `due_at` in the response.
```json
{
    "id": "a502674e-3f74-4d73-a839-cdfcfcf76fed",
    "paid_amount": "0.00",
}
```

All these cases look like bugs. Or maybe I'm wrong?

**Comment by rubenvanassche** [comment]
Hi @mlshvdv,

You're right, this feels a bit odd. But, includes/excludes/... are used throughout the code and sometimes defined as the properties in the data class like the `allowedRequestIncludes` method. I think what you're saying is correct, you should probably be able to use these properties with their mapped name in the request. Since the feature is working (not completely as expected) I don't see it as a bug, more a refinement that should be made.

I don't have the time at this moment to implement such a thing. But you or someone else is always welcome to implement such a thing, send in a fully tested PR and I'm 99% sure that I'll merge it.

As a staring point, before this step, the names of the properties in the partial trees should be mapped. And it should happen to nested data objects and collections:

https://github.com/spatie/laravel-data/blob/0a098fffd2ad30eb82e394f949da396a6fe886ab/src/Resolvers/PartialsTreeFromRequestResolver.php#L41

**Comment by mlshvdv** [comment]
@rubenvanassche Hi! Ok, I'll try to implement the support for this.

**Comment by rubenvanassche** [comment]
Thanks @mlshvdv, good luck!

**Comment by rubenvanassche** [comment]
Fixed with next release!
