### ISSUE TITLE
502 Bad Gateway on 3.2.2

### ISSUE THREAD

**Issue by benjivm** [spatie/laravel-data#397]
Upgrading to 3.2.2 results in a Bad Gateway on any request that uses Laravel Data, other requests are returned as expected. Downgrading to 3.2.1 resolves the issue.

How can I help troubleshoot this? I don't see anything in `laravel.log` related to this.

**Comment by rubenvanassche** [comment]
Do you have a circular dependency within your data objects and are you running including, excluding, except or only operations on these objects?

**Comment by rubenvanassche** [comment]
I've reverted this in 3.3.3, we'll need another look at this solution before we can use it.

**Comment by benjivm** [comment]
@rubenvanassche thanks, if you are unable to reproduce this I will take the time to setup a project to see if I can track down how this is happening in my use case.

**Comment by rubenvanassche** [comment]
I'm going to work on it within an hour, I think I know what the problem is because I've rewritten the original PR. But if I can't reproduce it then I'll certainly ping you, thanks!

**Comment by rubenvanassche** [comment]
New version tagged which should fix everything
