### ISSUE TITLE
Error when using resolve() with laravel-data classes

### ISSUE THREAD

**Issue by abdevcode** [spatie/laravel-data#458]
I am using your library to organize my data, but when I tried to create a data object using the resolve() function provided by laravel and passing the parameters needed to instantiate the data object did not work and was always using the parameters sent in the request.

Here is an example of what I am doing:
```
class ContactData extends Data
{
    public function __construct(
        public string $name,
        public string $email,
    )
    {}
}

resolve(ContactData::class, [
    'name' => 'Bob',
    'email' => 'bob@example.com',
]);
```

After some research, I could find the problem.
The problem is in the LaravelDataServiceProvider, because in the service provider binds the class and always uses the Request (except when you have your own bind defined).
```
        /** @psalm-suppress UndefinedInterfaceMethod */
        $this->app->beforeResolving(BaseData::class, function ($class, $parameters, $app) {
            if ($app->has($class)) {
                return;
            }

            $app->bind(
                $class,
                fn ($container) => $class::from($container['request'])
            );
        });
```

However, the parameter $paremeters is never used.

**Comment by verner-lall** [comment]
I am curious why even use resolve for that? Can you not use `ContactData::from($yourData)` or `ContactData::createAndValidate($yourData)` as documentation suggests?

**Comment by abdevcode** [comment]
Let me give an example of what I am doing.
Imagine that I have a house and I have animals (different type of animals with different properties)
The code would be something like this

```
interface Animal {}

class DogData extends Data implements Animal
{
    public string $class = self::class;

    public function __construct(
        public string $name,
        public string $color,
    ){}
}

class BirdData extends Data implements Animal
{
    public string $class = self::class;

    public function __construct(
        public string $name,
        public float $weight,
    ){}
}

class HouseData extends Data implements Animal
{
    public function __construct(
        public Animal $animal,
    ){}
}
```

So now I can have one animal in my house, doing this

```
        $bird = BirdData::from([
            'name' => 'Alice',
            'weight' => 12.34,
        ]);

        $dog = DogData::from([
            'name' => 'Bob',
            'color' => 'black',
        ]);

        $house = HouseData::from([
            'animal' => $bird,
        ]);

or

        $house = HouseData::from([
            'animal' => $dog,
        ]);
```

Now, I want to save this in the DB, to achieve that I am using `json_encode($house)`

```
"{"animal":{"class":"App\\Http\\Controllers\\BirdData","name":"Alice","weight":12.34}}"
"{"animal":{"class":"App\\Http\\Controllers\\DogData","name":"Bob","color":"black"}}"
```

Great! However... the problem is how to get the data object again from the `json_decode($data)`

That's why I am doing all this, I don't know if there any better way to achieve this behaviour

**Comment by koomai** [comment]
```
$data = json_decode($json, true);

$data['animal']['class']::from($data['animal']);
```

**Comment by rubenvanassche** [comment]
We do not support `resolve` with parameters at the moment. Use the solution koomai presents or write a custom creation method for string. Maybe the eloquent casts can be usefull?
