### ISSUE TITLE
Optional nested objects not working correctly

### ISSUE THREAD

**Issue by harrydoddnoble** [spatie/laravel-data#461]
I have the following code. The data object is created from a request which may or may not have an address in the payload.

```
class NewRegularUserDto extends Data
{
    public function __construct(
        #[Required] #[Email]
        public string $email,
        #[Required] #[StringType]
        public string $role,
        #[Required]
        public ProfileDto $profile,
        #[Sometimes]
        public AddressDto|Optional $address,
    ) {
    }
}
```

When it doesn't have an address in the payload I would expect it to create the data object without an address but it is throwing a validation error related to the validation in the AddressDTO. I also tried
`        public ?AddressDto $address = null,`

But it still tries to validate an address and returns an error.

How do I make it so that if there is an address in the payload it is validation and if there is no address then do not try to validate it and set $address to null. Is this linked to Issue #441 ?

**Comment by rubenvanassche** [comment]
I cannot reproduce this:

```php
it('ca', function(){
    class AddressDto extends Data{
        public function __construct(
            public string $a,
        )
        {
        }
    }

    class NewRegularUserDto extends Data
    {
        public function __construct(
            public AddressDto|Optional $address,
        ) {
        }
    }

    NewRegularUserDto::validate((new Request())->merge([])); // works
    NewRegularUserDto::validate((new Request())->merge(['address' => ['a' => 'b']])); // works
    NewRegularUserDto::validate((new Request())->merge(['address' => null])); // fails validation
});
```

Please provide me a test like this fails.

**Comment by harrydoddnoble** [comment]
It turns out that the latest version fixes this issue so I think it is OK now. I believe it must have been a bug in a prior version
