### ISSUE TITLE
DataCollection throws CannotCreateData instead of ValidationException

### ISSUE THREAD

**Issue by M-Hidalgo** [spatie/laravel-data#467]
**✏️ Describe the bug**

When we create a DataCollection for ex:`SomeData::collection($arrayPayload)` the exception being thrown when a property is missing is not a ValidationException and instead we get a CannotCreateData. In this scenario we are not using the SomeData::validateAndCreate($payload) since we need to create a collection, and it seems we are not actually processing the data mappings using the $validator.

**↪️ To Reproduce**

```
class SongData extends Data
{
    public function __construct(
        #[Rule(['required','string'])]
        public string $title,
        #[Rule(['required','string'])]
        public string $artist,
    ) {
    }
}

SongData::collection([
    ['title' => 'Some title'],
    ['title' => 'Some other title', 'artist' => 'Some artist'],
]);
```

This will throw a CannotCreateData exception and provide a different message, than it would with the ValidationException which we can overwrite the validation message for.

**✅ Expected behavior**
Allow DataCollections when fail to create to throw the ValidationException with the custom message provided.

**🖥️ Versions**

Laravel: 9.52
Laravel Data: v3
PHP: 8.1

**Comment by rubenvanassche** [comment]
This does not look like a bug to me, by default from will also not validate this payload and crash immediately. Only when passing a request object into from method or explicitly call `validateAndCreate`. 

It's actually the same with collections, although no `validateAndCreate` method exists on it. That's something we could maybe add in the future, I'm always open for well tested PR's.

As for the whole validation problem, all of this could maybe fixed within v4 if we manage to implement this one: https://github.com/spatie/laravel-data/discussions/470
