### ISSUE TITLE
Unnecessary validation of optional fields causes errors

### ISSUE THREAD

**Issue by Freeeon** [spatie/laravel-data#480]
**✏️ Describe the bug**
I create Data with optional field and default value like [here](https://spatie.be/docs/laravel-data/v3/as-a-data-transfer-object/defaults). I use validateAndCreate — Data always falls, when I skip this field. I trying use Nullable attribute — same behavior. 
Only works when I use type string|Optional, but there is no hint about it on the documentation page.

It's important for me use validateAndCreate in this case, because I have a lot of fields and validate all of them, except default field. 

**↪️ To Reproduce**

```php

class DocumentData extends Data
{
    public function __construct(
        #[Nullable]
        public string $type = "passport",
    ) {}
}

it('can create data without optional field', function () {
    DocumentData::validateAndCreate([]);
});
```

```
Illuminate\Validation\ValidationException: The type field is required.
/var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php:328
/var/www/html/vendor/laravel/framework/src/Illuminate/Validation/Validator.php:503
/var/www/html/vendor/spatie/laravel-data/src/Concerns/ValidateableData.php:30
/var/www/html/vendor/spatie/laravel-data/src/Concerns/ValidateableData.php:52
/var/www/html/tests/Traits/ClientTrait.php:14
/var/www/html/tests/Feature/CreateClientTest.php:35
/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:174
```
**✅ Expected behavior**
Create Data with default field

**🖥️ Versions**

Laravel: 10.13
Laravel Data: 3.6.0
PHP: 8.2.7

**Comment by rubenvanassche** [comment]
This should be fixed with the release later today!
