### ISSUE TITLE
All fields are always being validated when using Laravel Precognition

### ISSUE THREAD

**Issue by Slund** [spatie/laravel-data#484]
**✏️ Describe the bug**
When you accept a Laravel-Data class as the paramater in a controller that uses the HandlePrecognitiveRequests-middleware, it always validates all fields in the class, instead of only the ones it should.

**↪️ To Reproduce**
Setup Breeze with Vue, TS and Inertia. Add HandlePrecognitiveRequests to the register route (method: post) in auth.php.

```php
    Route::post('register', [RegisteredUserController::class, 'store'])
        ->middleware([HandlePrecognitiveRequests::class]);
```

Then create a Laravel-Data class with the following content:
```php
class StoreUserDTO extends Data
{
    public function __construct(
        public string $name,
        public string $email,
        public string $password
    )
    {}

    public static function rules(): array
    {
        return [
            'name' => 'string|max:1',
            'email' => 'string|max:1',
        ];
    }
}
```

Accept the class as a parameter in the method store, in RegisteredUserController.
```php
public function store(StoreUserDTO $request)
```

Make the Vue component Auth/Register.vue use Precognition
```typescript
...
import { useForm } from 'laravel-precognition-vue-inertia';

const form = useForm('post', '/register', {
    name: '',
    email: '',
    password: '',
    password_confirmation: '',
});

const submit = () => {
    form.submit();
};
...
```

And setup the name field to validate itself on change:
```typescript
@change="form.validate('name')"
```

When you enter something in the name field and goes on it validates all fields:
```json
{
    "message": "The email field must be a string. (and 1 more error)",
    "errors": {
        "email": [
            "The email field must be a string."
        ],
        "password": [
            "The password field is required."
        ]
    }
}
```

**✅ Expected behavior**
I would it expect it to only validate the name field. If you instead accept a FormRequest in the controller parameter, with the same validation it works as intended:
```php
class StoreUserRequest extends FormRequest
{
    public function rules(): array
    {
        return [
            'name' => 'string|max:1',
            'email' => 'string|max:1',
        ];
    }
}
```

I know that you can't expect an open-source package to work out-of-the-box with every other package, so this definitely is not to flame or anything like that (I absolutely love all of your stuff!).
However it could be great if a great package like Laravel-Data could work together with Laravel Precognition.
So I wanted to know if this is an issue anyone has a workaround for or is looking into fixing.

If not, and it is something you want to have support for, I could attempt to find time for a PR during the summer. 

**🖥️ Versions**

Laravel: 10.14.0
Laravel Data: 3.6
PHP: 8.2.6

**Comment by rubenvanassche** [comment]
Hi @Slund,

Yeah data isn't working with precognition at the moment, something we"ll certainly add in v4 later on this year. But if I'm not mistaken, precognition is still in beta phase and Taylor promised a complete rewrite which isn't released as fas as I'm aware so not entirely sure if we already can start developing the feature.

I'm gonna close this for now but rest assured we'll implement this, it's already on our validation roadmap: #470

**Comment by Slund** [comment]
Ok cool! Good to know.

I believe the rewrite has happened hence: https://twitter.com/taylorotwell/status/1661072219618045952?s=20 and it's also a part of the official documentation now: https://laravel.com/docs/10.x/precognition

Thanks for the answer and the great work with this package!

**Comment by adwinying** [comment]
Hi @rubenvanassche, is Precognition currently supported in v4?

**Comment by rubenvanassche** [comment]
Nowp will be more something for v5 since a lot of breaking changes are required. V4 was already such a massive release we decided not to include it into it.

**Comment by Slund** [comment]
> Hi [@rubenvanassche](https://github.com/rubenvanassche), is Precognition currently supported in v4?

There is a workaround here: https://github.com/spatie/laravel-data/discussions/343
We are using it successfully.
