### ISSUE TITLE
Cannot Create Nullable Computed Properties

### ISSUE THREAD

**Issue by nickpoulos** [spatie/laravel-data#529]
**✏️ Describe the bug**
You cannot create computed properties that are nullable. 

**↪️ To Reproduce**
Provide us a pest test like this one which shows the problem:

```php

it('cannot have nullable computed properties', function () {
    class TestDataA extends Data
  {
      #[Computed]
      public ?string $url;
  
      public function __construct(
          public array $stuff,
      ) {
          $this->url = $this->stuff['link_url'] ?? null;
      }
  }

class TestDataB extends Data
  {
      #[Computed]
      public string $url;
  
      public function __construct(
          public array $stuff,
      ) {
          $this->url = $this->stuff['link_url'] ?? null;
      }
  }

    // TestDataA Throws an exception for Cannot Set Computed Property

   // TestDataB works correctly because we make the ?string non-nullable

   // However I would like to use this for data where `link_url` key might not be in '$stuff' and return null in that case

    dd(
TestDataA::validateAndCreate([
  'stuff' => ['link_url'=> 'google.com']
]),

TestDataB::validateAndCreate([
  'stuff' => ['link_url'=> 'google.com']
])
});
```

**✅ Expected behavior**
I would expect computed properties to be allowed to be set to nullable. Optional is not the same. 

**🖥️ Versions**

Laravel: 10x
Laravel Data: 3.7
PHP: 8.2

**Comment by micmek** [comment]
I'm having the same issue. I get an error message
`Cannot set property UserData::$phone because it is a computed property.`
But the phone property can be null so it should allow it to be nullable

`/** @var string|null  */
    #[Computed]
    public ?string $phone;`

**Comment by nickpoulos** [comment]
Yes agreed, seems like there are real world use cases where this behavior would be useful. I am having a hard time thinking of reasons why we may not want to allow this.

**Comment by rubenvanassche** [comment]
Will be fixed in the next release, not really a reason why we didn't support it.
