### ISSUE TITLE
Custom validation attribute problem.

### ISSUE THREAD

**Issue by nortmas** [spatie/laravel-data#535]
**✏️ Describe the bug**
I'm not sure if it's a bug or a documentation issue.
I'm trying to create a custom validation attribute, like it's said in https://spatie.be/docs/laravel-data/v3/advanced-usage/validation-attributes#content-creating-your-validation-attribute

```php

use Spatie\LaravelData\Support\Validation\ValidationRule;

#[Attribute(Attribute::TARGET_PROPERTY)]
class ValidPasswordRule extends ValidationRule
{
    public function getRules(): array
    {
        return [new ValidPassword()];
    }
}

```

The confusing thing in the documentation is that "CustomRule" class name returns itself, but I guess It should return another class CustomRule that implements the interface Illuminate\Contracts\Validation\ValidationRule, am I right?

I'm doing it, but I'm getting the error: `Illuminate\Validation\ValidationRuleParser: 134: Object of class App\Rules\ValidPasswordRule could not be converted to string. `

After several attempts, I was able to make it working:

```php

use Attribute;
use Spatie\LaravelData\Attributes\Validation\ObjectValidationAttribute;
use Spatie\LaravelData\Support\Validation\ValidationPath;

#[Attribute(Attribute::TARGET_PROPERTY)]
class ValidPasswordRule extends ObjectValidationAttribute
{
    public function getRule(ValidationPath $path): object|string
    {
        return new ValidPassword();
    }

    public static function keyword(): string
    {
        return 'validPassword';
    }

    public static function create(string ...$parameters): static
    {
        return new static();
    }
}
```

**Comment by rubenvanassche** [comment]
Hmmm, this is still a relic from the past. These rules have been completely rewritten to use Laravel standards but that makes them complicated to built yourself.

I've added a new `CustomValidationAttribute` which makes things a lot easier, should be released later today.

**Comment by dmitry-buzzwoo** [comment]
awesome, thank you!

**Comment by dmitry-buzzwoo** [comment]
@rubenvanassche Could you please update the Doc? Thank you 👍🏼

**Comment by rubenvanassche** [comment]
You can find it here: https://github.com/spatie/laravel-data/blob/d21e6c7b67e3a0dcc425d70e9e860316ccd643e3/docs/advanced-usage/validation-attributes.md#L21

Strangely enough the data docs aren't updating on the Spatie website. Going to take a look.

**Comment by rubenvanassche** [comment]
Looks updated now
