### ISSUE TITLE
RequiredIf validator does not work properly if field is Optional

### ISSUE THREAD

**Issue by akimkelar** [spatie/laravel-data#536]
**↪️ To Reproduce**
Imagine, we have a data object with three fields

```
    #[Required]
    #[BooleanType]
    public bool $success;

    #[RequiredIf('success', 'false')]
    #[StringType]
    public string $error = '';
   
    #[RequiredIf('success', 'true')]
    #[IntegerType]
    public Optional|int $id;
```

The first one (success) represents the state of the data state, is it successful or not.
The second one (error) has to have a description if the state is not successful.
The third one (ID) has to contain the resulting value if the state is successful.

**✏️ Describe the bug**
The error works as expected – it is required if success = false.
But the ID will produce no validation errors with data set ['success' => true], because of Optional (the rules set will contain 'Sometimes' rule, and because of it passesOptionalCheck will be failed, and field become not validatable)

**✅ Expected behavior**
The ID field should be provided only if the operation was successful.
It means on set like ['success' => false, 'error' => 'failed'], the ID is really Optional.
But on set ['success' => true] the validation should throw an exception because the ID is required on successful data set. 

**🖥️ Versions**

Laravel: 
"name": "laravel/framework",
            "version": "v9.52.10",
Laravel Data:
 "name": "spatie/laravel-data",
            "version": "3.6.0",
PHP:
8.1

**Comment by rubenvanassche** [comment]
Hi @akimkelar,

We cannot fix this in v3 since it would break a lot, automatically deducing these rules is really hard. I've added a test for v4 which we'll try to solve in that version.

In the meantime, you can always overwrite validation rules by implementing a custom rules method on the data class. Adding the correct rules over there is the easiest fix for now.
