### ISSUE TITLE
EnumCast doesn't work with UnitEnum

### ISSUE THREAD

**Issue by hfoletto** [spatie/laravel-data#540]
**✏️ Describe the bug**
EnumCast doesn't work with UnitEnum, it only works with backed enums.

**↪️ To Reproduce**
1. Create a new laravel project
2. Install this package
3. Create an Enum with the following content
```php
enum Format {
    case cd;
    case vinyl;
    case cassette;
}
```
4. Create a data class with the following content:
```php
class SongData extends Data
{
    public function __construct(
        public string $title,
        public string $artist,
        #[WithCast(EnumCast::class)]
        public Format $format,
    ) {
    }
}
```
5. Test it using tinker:
```php
App\Data\SongData::from([
    'title' => 'Never gonna give you up',
    'artist' => 'Rick Astley',
    'format' => 'vinyl',
]);
```
6. Observe error:
```
TypeError  App\Data\SongData::__construct(): Argument #3 ($format) must be of type App\Enums\Format, Spatie\LaravelData\Casts\Uncastable given, called in vendor/spatie/laravel-data/src/Resolvers/DataFromArrayResolver.php on line 72.
```
7. Try adding a type param to the cast:
```php
class SongData extends Data
{
    public function __construct(
        public string $title,
        public string $artist,
        #[WithCast(EnumCast::class, type: Format::class)]
        public Format $format,
    ) {
    }
}
```
8. Observe different error:
```
Spatie\LaravelData\Exceptions\CannotCastEnum  Could not cast enum: `vinyl` into a `App\Enums\Format`.
```
**✅ Expected behavior**

The steps to reproduce are actually from the documentation: https://spatie.be/docs/laravel-data/v3/as-a-data-transfer-object/casts

Since in the documentation it shows an UnitEnum being used with the EnumCast, I expected it to work and not see those errors. Looking at the code, looks like there is even a test to ensure the EnumCast shouldn't work with UnitEnum, which is confusing: https://github.com/spatie/laravel-data/blob/main/tests/Casts/EnumCastTest.php#L37

I'm wondering if there is a specific reason for it to not work with UnitEnums, and if there is not then I can work on a PR to fix this behavior.

**🖥️ Versions**

Laravel: v10.20.0
Laravel Data: 3.8.1
PHP: v8.2.9

**Comment by rubenvanassche** [comment]
Yeah the documentation is wrong here, UnitEnums cannot be created from strings since that doesn't make sense. I've update the docs

**Comment by hfoletto** [comment]
> Yeah the documentation is wrong here, UnitEnums cannot be created from strings since that doesn't make sense. I've update the docs

@rubenvanassche I think it's possible to create UnitEnums from strings, that's how Laravel handle the Enum cast.
https://github.com/laravel/framework/blob/10.x/src/Illuminate/Database/Eloquent/Casts/AsEnumCollection.php
```php
return is_subclass_of($enumClass, BackedEnum::class)
    ? $enumClass::from($value)
    : constant($enumClass.'::'.$value);
```

But if that's something that's not desirable to have in this package, no problems, just wanted to confirm since the docs were a bit confusing.

**Comment by rubenvanassche** [comment]
Yeah, I know it is technically possible but in such a case I think we should move users to just use a string backed enums. In the long run using strings as UnitEnums will give you problems when refactoring. Better try to teach people who just started some good ideas by not allowing this operation 😄

**Comment by hfoletto** [comment]
Gotcha, that makes sense!
