### ISSUE TITLE
Class must be declared abstract or implement method 'getMorphClass' from 3.8.0 release

### ISSUE THREAD

**Issue by ccorreia64** [spatie/laravel-data#548]
When updating the vendor I am getting that message. In BaseData interface has this method

```
vendor/space/laravel-data/src/Contracts/BaseData.php

public function getMorphClass(): string;
```

Do I have to implement that method in every dto?

<img width="711" alt="image" src="https://github.com/spatie/laravel-data/assets/5826696/a9f2f0c1-51c5-4ff2-9f94-6921c5dc019c">

**🖥️ Versions**

Laravel: 10.21.0
Laravel Data: 3.8.1
PHP: 8.2.8

**Comment by ccorreia64** [comment]
Closing the issue, the IDE stopped showing that warning..

**Comment by opcodespace** [comment]
I see the same problem in my phpStorm. @ccorreia64  How did you fix this issue?

**Comment by ccorreia64** [comment]
> I see the same problem in my phpStorm. @ccorreia64 How did you fix this issue?

After update this vendor, I ran the `php artisan ide-helper:generate` command, since I use that vendor. 
Closed the IDE and when I opened it, that warning disappeared..
