### ISSUE TITLE
MimeTypes validation fails on v1

### ISSUE THREAD

**Issue by SergeyYemielianovGC** [spatie/laravel-data#595]
**✏️ Describe the bug**
Validation Attribute `MimeTypes` fails.
```
exception: "BadMethodCallException"
file: "/vendor/laravel/framework/src/Illuminate/Validation/Validator.php"
line: 1555
message: "Method Illuminate\\Validation\\Validator::validateMimestypes does not exist."
```

**↪️ To Reproduce**

```php
    class FileData extends Data
    {
        #[File]
        #[MimeTypes('image/jpeg')]
        public function __construct(
            public UploadedFile $file,
        ) {
        }
    }

    dd(FileData::validate([
        'file' => UploadedFile::fake()->image('photo1.jpg')
    ]));
```

**✅ Expected behavior**
An instance of `FileData` should be created and displayed as a `dd` call result.

I believe this is caused by a typo in `src/Attributes/Validation/MimeTypes.php` on the line 20. It should be `mimetypes` instead of `mimestypes`
![image](https://github.com/spatie/laravel-data/assets/57894068/4f247f1f-1c66-484d-8ed0-d27e651bf6e2)

**🖥️ Versions**

Laravel: 9.52.16
Laravel Data: 1.5.2
PHP: 8.1.24

**Comment by rubenvanassche** [comment]
Thanks for the PR, normally we do not support v1 anymore but since you Pr'ed and it's such an easy fix I've made a new release.
