### ISSUE TITLE
Custom validation attribute is not working

### ISSUE THREAD

**Issue by zavvdev** [spatie/laravel-data#598]
**✏️ Describe the bug**
I have a `username` field in my User model and I want to create reusable validation rule for it since i'm going to use it in a different places. I'm following this part of documentation: https://spatie.be/docs/laravel-data/v3/advanced-usage/validation-attributes#content-creating-your-validation-attribute. 

My custom rule:

```
<?php

namespace App\Http\ValidationRules\User;

use Attribute;
use Spatie\LaravelData\Attributes\Validation\Max;
use Spatie\LaravelData\Attributes\Validation\Min;
use Spatie\LaravelData\Attributes\Validation\Regex;
use Spatie\LaravelData\Attributes\Validation\Unique;
use Spatie\LaravelData\Support\Validation\ValidationRule;

#[Attribute(Attribute::TARGET_PROPERTY)]
class UsernameRule extends ValidationRule
{
    public function getRules(): array
    {
        return [
            new Min(3),
            new Max(16),
            new Unique('users', 'username'),
            new Regex("/^\w*$/")
        ];
    }
}
```

And then I'm using it in my Request data:

```
class RegisterRequest extends RequestData
{
    public function __construct(
        #[Required, Email, Unique('users', 'email')]
        public string $email,

        #[Required, UsernameRule]
        public string $username,

        #[Required, Confirmed, Password]
        public string $password,
    ) {
    }
}
```

But when I did a request to the endpoint I got next error message: 
 `"Object of class App\\Http\\ValidationRules\\User\\UsernameRule could not be converted to string"`

So, it looks like it wants me to create a `__toString` method which returns a laravel validation string. I did so by imploding an array from `getRules` method:

```
public function __toString()
    {
        return implode("|", $this->getRules());
    }
```

And got next error:
`The given value \"3|max:16\" does not represent a valid number.`.

It's because Min and Max rules are converted into "min:3" and "max:16" but I'm using them with string to check the length. 

So, did I miss something or it's just a bug within the package? 

**🖥️ Versions**

Laravel: 10.10
Laravel Data: 3.9
PHP: 8.2.12

**Comment by mrtijn** [comment]
Just encountered the same issue. Fixed it by using:
https://github.com/spatie/laravel-data/issues/535
