### ISSUE TITLE
Unable to cast property of collection with strings

### ISSUE THREAD

**Issue by megawubs** [spatie/laravel-data#619]
**✏️ Describe the bug**
I'm unable to use a `Collection<array-key, string>` with Laravel data

**↪️ To Reproduce**

```php
use Illuminate\Support\Collection;

it('cannot create collection from array', function () {
    class ChildData extends Data
    {
        public function __construct(
            public string $name,
            public Collection $names,
        ) {
        }
    }


     ChildData::from(['name' => 'Bram', 'names' => ['Jan', 'Hendrik', 'Piet']]); //exception: collection required, array given
});
```

**✅ Expected behavior**
I expect Laravel data to be smart enough to cast the given array into a collection. Or to provide me a cast to annotate it myself

**🖥️ Versions**

Laravel: 9.52.16
Laravel Data: 3.9.2
PHP: 8.2.11

**Comment by pepperfm** [comment]
@rubenvanassche if this issue is relevant, i want to try to fix it. So tell me your decision.

I will be waiting for your reply. Thanks.

**Comment by rubenvanassche** [comment]
Good point, added this as a feature, probably release it later today as data v4.0.1, don't forget to update the config file with the new cast.

**Comment by fnzr** [comment]
Sorry to necro, but what is the new config mentioned on "don't forget to update the config file with the new cast." ?

The test case in the opening post continues to fail on v4.9.0 with default config and I couldn't find which cast/config is associated with this
