### ISSUE TITLE
Wireable rich data object issue with Computed property on Livewire component refresh

### ISSUE THREAD

**Issue by Neoglyph** [spatie/laravel-data#621]
**✏️ Describe the bug**
Using a Wireable rich data object that contains a Computed property in a Livewire component breaks the refresh of the component.

**↪️ To Reproduce**
Example project is available here: [https://github.com/Neoglyph/spatie-data-wireable-issue-2023-12-21](https://github.com/Neoglyph/spatie-data-wireable-issue-2023-12-21)

If downloading is not an option the issue is provided below with a PEST test.

UserData.php
```php
namespace App\Data;

use Livewire\Wireable;
use Spatie\LaravelData\Attributes\Computed;
use Spatie\LaravelData\Concerns\WireableData;
use Spatie\LaravelData\Data;

class UserData extends Data implements Wireable
{
    use WireableData;
    
    #[Computed]
    public string $name;

    public function __construct(
        public string $firstName,
        public string $lastName,
    ) {
        $this->name = "{$this->firstName} {$this->lastName}";
    }
}
```

UserDisplay.php
```php
namespace App\Livewire\Component;

use App\Data\UserData;
use Livewire\Component;

class UserDisplay extends Component
{
    public UserData $user;

    public function mount()
    {
        $this->user = new UserData(
            firstName: 'Adam',
            lastName: 'Stradovnik',
        );
    }

    public function render()
    {
        return view('livewire.component.user-display');
    }
}
```

user-display.blade.php
```blade
<div class="text-white text-center">
    {{ $user->name }}
    <br><br>
    <button type="button" wire:click="$refresh">
        Refresh component
    </button>
</div>
```

```php
use function Pest\Livewire\livewire;

it('throws CannotSetComputedValue exception on component refresh', function () {
    $this->expectException(CannotSetComputedValue::class);

    livewire(UserDisplay::class)
        ->call('$refresh');
});
```

**✅ Expected behavior**
The Livewire component should refresh without an issue.

**🖥️ Versions**

Laravel:  v10.38.1
Laravel Data: 3.10.1
PHP: 8.2.12

**Comment by rubenvanassche** [comment]
Hi,

Could you test this again with the new data synths introduced a few days ago?

**Comment by rubenvanassche** [comment]
Hi, since this issue is inactive for quite some time I'm going to close this. Feel free to answer later on and I'll take a further look.
