### ISSUE TITLE
Consider ignore abstract classes in the `data:cache-structures` command

### ISSUE THREAD

**Issue by josecl** [spatie/laravel-data#623]
I have some abstract classes extending `Data` with a partial implementation:

```php
abstract class ReceptoresDirectorioData extends Data
{
    public DataCollection $receptores;
}
```

The command `php artisan data:cache-structures` fails with the Exception `CannotFindDataClass`: `Data collection property receptores in ... has an annotation that isn't a data object or is missing an annotation`.

Moving this to a PHPDoc fixes the issue for my case, but I think in general the cache command should ignore abstract classes.

**Comment by rubenvanassche** [comment]
Could you test this in v4, I think we stopped throwing these exceptions.
