### ISSUE TITLE
Creating a Data object having DataCollectionOf casting with specified named argument "class" fails

### ISSUE THREAD

**Issue by helloimsergio** [spatie/laravel-data#625]
Creating a Data object having `DataCollectionOf` casting with specified named argument `class` throws `ErrorException` with message: `Undefined array key 0` at file `Spatie\LaravelData\Support\DataType:247`

**↪️ To Reproduce**

```php

class EmailData extends Data {
    public function __construct() {
        public string $email,
    }
}

class ContactsData extends Data {
    public function __construct() {
        #[DataCollectionOf(class: EmailData::class)]
        public DataCollection $emails,
    }
}

$contacts = ContactsData::from(['emails' => ['email' => 'email@example.com']]);

```

**🖥️ Versions**

Laravel: 10.38.2
Laravel Data: 3.11.0
PHP: 8.2.10

**Comment by rubenvanassche** [comment]
Can't reproduce on v4, there is a bug in your test BTW, this should be correct:

it('bla', function () {
    class EmailData extends Data
    {
        public function __construct(
            public string $email
        ) {

        }
    }

    class ContactsData extends Data
    {
        public function __construct(
            #[DataCollectionOf(class: EmailData::class)]
            public DataCollection $emails,
        ) {

        }
    }

    $contacts = ContactsData::from(['emails' => [['email' => 'email@example.com']]]);

    dd($contacts);
});
