### ISSUE TITLE
Application tests that use Cache mocking fail since PR #622 (v3.11.0)

### ISSUE THREAD

**Issue by jaydublu2002** [spatie/laravel-data#641]
Prior to 3.11.0 which adds support for data structure caching https://github.com/spatie/laravel-data/pull/622, our application test suite inculdes use of Cache mocking for some tests, specifically where Cache::remember() is used in code and tests emulate cache hits.

Since 3.11.0 these tests are now failing because our mocking doesn't cover calls made by this package. 

Is there a way to disable this feature for tests, or advice how to extend our mock expectations so tests pass again?

**↪️ To Reproduce**

In our application, our api client (using [Saloon](https://docs.saloon.dev/)) has a method that caches a bearer token used to access an external api, using `Cache::remember`

```php
    public static function bearerToken(): string
    {
        return Cache::remember('importservice-bearer-token', 23 * 60 * 60, function () {

            // functionality that obtains a bearer token

            return 'some_access_token';
        });
    }

```

In this example feature test, we mock the call to `Cache::remember` assuming that we already have a valid bearer token cached (this is tested elsewhere)

```php

    public function test_getJobs()
    {
        // Stops Saloon trying to get a bearer token
        Cache::shouldReceive('remember')
            ->andReturn('cached-token');

        Saloon::fake([
            GetJobsRequest::class => MockResponse::fixture('jobs-index'),
        ]);

        // act

        // makes an api call including the bearer token in the request header,
        // and maps the response to a collection of Data objects
        $response = ImportService::getJobs();

        // assert

        Saloon::assertSent('/jobs');

        $this->assertEquals(145, count($response));
    }

```

Error message:

`Received Mockery_2_Illuminate_Cache_CacheManager::store(), but no expectations were specified`

**✅ Expected behavior**

Test passes

**🖥️ Versions**

Laravel: 10.41.0
Laravel Data: 3.11.0
PHP: 8.1.4

**Comment by rubenvanassche** [comment]
I've added a disabled config option in data v4 (4.0.1 probably released later today), if you disable it the cache won't be used. Also caching won't be performed when unit testing.
