### ISSUE TITLE
Validation fails when initializing a data object with a nested instantiated dataobject

### ISSUE THREAD

**Issue by hxnk** [spatie/laravel-data#655]
**✏️ Describe the bug**
Validation fails when initializing a data object with a nested instantiated dataobject

**↪️ To Reproduce**
```php

it('should probably pass validation here', function () {

    class BaseData extends Data
    {
        public function __construct(
            public ChildData $child,
        ) {
        }
    }

    class ChildData extends Data
    {
        public function __construct(
            public string $name,
        ) {
        }
    }

    // Illuminate\Validation\ValidationException: The child field must be an array. (and 1 more error)
    BaseData::factory()->alwaysValidate()->from([
        'child' => new ChildData('Spatie'),
    ]);

});
```

**✅ Expected behavior**
I expect validation to pass

**🖥️ Versions**

Laravel: 10.x
Laravel Data: 4.0.0
PHP: 8.3

**Comment by rubenvanassche** [comment]
This is correct behavior, the validator can only validate what Laravel can validate. A data object cannot be validated by Laravel itself.

Technically we could transform this structure into an array again and validate that, but that would not be that performant + when passing another object we never can do more than the Laravel validator can.

Tricky situation I know but sadly enough we can't do anything about it 😞

**Comment by hxnk** [comment]
@rubenvanassche Wouldn't it make sense to simply not validate nested data objects when they are instantiated already, maybe it should be assumed the user knows what they are doing, and it is in a valid state? 🤔

**Comment by rubenvanassche** [comment]
Hmm I think the reverse can also be said, if you've created the objects yourself from a request and then passed them to a data object to be validated are they still valid?

If someone finds a way to validate these things without compromising on performance, I would certainly merge such a PR but at the moment we're not using it that way so I don't have the time available to build such a thing.

**Comment by jbeales** [comment]
Just ran into this myself and ended up here.

I think that since validation always happens before the DTO is created there's a good argument for accepting that an instantiated DTO of the correct type should be considered valid - in fact, the [docs do say](https://spatie.be/docs/laravel-data/v4/validation/introduction#content-when-does-validation-happen) "once a data object is created, it is assumed that the data is valid." 

That said, my current workaround for things that I will always supply as a DTO is going to be to add `#[WithoutValidation]` to those properties.

**Comment by bkremenovic** [comment]
I encountered a similar issue in my project and have been exploring potential solutions.

Is it possible to configure Laravel Data in the config file to convert the Data instance into an array, validate it, and then recreate it? I understand this might not be the most performance-efficient approach.
