### ISSUE TITLE
Disable structure caching variable logic

### ISSUE THREAD

**Issue by jaydublu2002** [spatie/laravel-data#664]
Further to issue #641 

**✏️ Describe the bug**
Is the logic in the fix in v4.0.1 for disabling sturcture caching correct? It does disable caching in unit tests (thanks, that resolved #641) but it looks to me like it also disables caching if `config('data.structure_caching.enabled')` is true.

Should it not be:

```php
        $this->app->singleton(
            DataConfig::class,
            function () {
                if (!config('data.structure_caching.enabled') || $this->app->runningUnitTests()) {
                    return DataConfig::createFromConfig(config('data'));
                }

                return $this->app->make(DataStructureCache::class)->getConfig() ?? DataConfig::createFromConfig(config('data'));
            }
        );
```
Also, is it possible to put this fix in the v3.x branch so we can update to latest v3.x - we have to do some refactoring of our appllication with regards to the way v4.x has changed how data is passed to / from collections.

**Comment by jaydublu2002** [comment]
I've also just noticed the documentation site https://spatie.be/docs/laravel-data/v4/installation-setup hasn't caught up with the new config variable

**Comment by rubenvanassche** [comment]
Thanks for the heads up, fixed!

As for v3, you're always welcome to send in a PR.

**Comment by jaydublu2002** [comment]
> As for v3, you're always welcome to send in a PR.

You could use PR #645?
