### ISSUE TITLE
PHPStorm requires implementation of abstract methods

### ISSUE THREAD

**Issue by Freeeon** [spatie/laravel-data#670]
**✏️ Describe the bug**
PHPStorm shows an error for any class, that extend Data. 

```
Class must be declared abstract or implement methods 'castUsing', 'jsonSerialize', 'allowedRequestOnly', 
'toArray', 'allowedRequestIncludes', 'all', 'allowedRequestExcludes', 'toJson', 'allowedRequestExcept' 
```

**🖥️ Versions**
Laravel Data: 4.1.0
PHP: 8.3
PHPStorm: 2024.1 EAP

<img width="811" alt="image" src="https://github.com/spatie/laravel-data/assets/5333602/e0d5270e-e8a8-4591-a6b4-7588fdecadfb">

**Comment by rubenvanassche** [comment]
This has something to do with PHPStorm incorrectly caching stuff, it cannot handle multiple traits + interface combinations right. Sadly nothing we can do about it.

The code should be working
