### ISSUE TITLE
Wrapping collections doesn't work as expected

### ISSUE THREAD

**Issue by santigarcor** [spatie/laravel-data#672]
**✏️ Describe the bug**
I'm getting a list of models, and when I try to wrap that list as it's stated in the docs, I get and array with one value being the string wrapper defined. It only works if I specifically say the collect method to use the DataCollection class.

**↪️ To Reproduce**
Provide us a pest test like this one which shows the problem:

```php
it('doesnt wrap collections correctly', function () {
    class TestData extends \Spatie\LaravelData\Data
    {
        public function __construct(
            public string $name,
        ) {
        }
    }

    $collection = \Illuminate\Support\Collection::make([
        ['name' => 'name 1'],
        ['name' => 'name 2'],
        ['name' => 'name 3'],
    ]);

    dd(TestData::collect($collection)->wrap('data'));
});
```

This will output:
<img width="299" alt="image" src="https://github.com/spatie/laravel-data/assets/7565417/7e14f549-500b-4487-b316-c5e07c845a9f">

**✅ Expected behavior**
To correctly wrap the data, or make the annotation on the docs that we need to specify the DataCollection for it to work like that

**🖥️ Versions**

Laravel:10.44.0
Laravel Data:4.1.0
PHP:8.3.2

**Comment by rubenvanassche** [comment]
Yeah, you can open a PR for updating the docs, the only way to perform such operations is on a DataCollection.
