### ISSUE TITLE
lazy properties not resolved correctly

### ISSUE THREAD

**Issue by edgars-vasiljevs** [spatie/laravel-data#677]
**✏️ Describe the bug**
lazy properties break when empty nested object is encountered.
After null, `{id,type}` is applied to main object instead of nested one. 

It's something to do with "rollBackPartialsWhenRequired" not being called if nested object is null.

**↪️ To Reproduce**

```php
// dto
class TagData extends Data
{
    public function __construct(
        public Lazy|int $id,
        public Lazy|TagType $type, // int enum
        public Lazy|TagData|null $parent,
    ) {
    }

    public static function fromModel(Tag $tag): TagData
    {
        return new static(...[
            Lazy::create(fn () => $tag->id),
            Lazy::create(fn () => $tag->type),
            Lazy::create(fn () => $tag->parent ? TagData::from($tag->parent) : null),
        ]);
    }
}

// generate object
$data = TagData::collect($collection, DataCollection::class)
    ->include('id', 'parent.{id,type}');
```

Result:
![image](https://github.com/spatie/laravel-data/assets/456317/8ea0b658-9ca7-4583-aaec-145a6f6b2eb0)

**✅ Expected behavior**
expect null to be null and any existing objects be resolved by given include/exclude rules.

**🖥️ Versions**

Laravel: 10.10
Laravel Data: 4.2.0
PHP: 8.2.9

**Comment by rubenvanassche** [comment]
Hi, could you update your test so that it doesn't use a model to show the issue. Providing an array with some default values looks like the easiest solution here.

**Comment by Tofandel** [comment]
I have the same/similar issue, I'll submit a failing test as a PR

**Comment by Tofandel** [comment]
@edgars-vasiljevs Can you test with my PR to see if it fixes your issue as well

**Comment by rubenvanassche** [comment]
This should be fixed normally! Let me know if it is not the case
