### ISSUE TITLE
Required non-constructor property is not really required and sets null if is nullable 

### ISSUE THREAD

**Issue by olexoliinyk0** [spatie/laravel-data#684]
**✏️ Describe the bug**
The main approach on how to describe DTO according to the docs is using the promoting constructor. But then in some parts of the docs there are [examples](https://spatie.be/docs/laravel-data/v4/as-a-data-transfer-object/collections#content-creating-a-data-object-with-collections) that make you believe that using class-level properties will also work, and it does! But..

There's a significant (unwanted) difference in the behavior, because it allows you to create the DTOs using `::from` without passing required properties, does not include them in the `->all` and `->toArray` results, and sets nullable non-set properties to be null if them don't have `Optional` type (and includes them in the `->all` and `->toArray` results with nulls), which is strange at least. 

**↪️ To Reproduce**
Say we have this example where properties listed in the class, not in the constructor, none of which is Optional, and one is nullable:

```php
use App\Data\SongData;
use Illuminate\Support\Collection;

class SongData extends Data
{    
    public string $title;
}

class AlbumData extends Data
{    
    public ?string $title;
    /** @var Collection<int, SongData> */
    public Collection $songs;
}

// you might think it will throw an Error, because none of the required fields are passed, but it won't
$albumData = AlbumData::from([]);

// even more - it sets the $title to `null` automatically
dd($albumData->toArray()); // --> ["title" => null]
```

If you add Optional to the nullable property it fixes the "set null" issue (but makes working with that property much less enjoyable): that is from `public ?string $title;` to `public string|Optional|null $title;` - now it does not sets it to null automatically and does not return in `toArray` calls.

If you rewrite it like this using the promoting constructor:

```php
use App\Data\SongData;
use Illuminate\Support\Collection;

class SongData extends Data
{
    public function __construct(
        public string $title,
    ) {}
}

class AlbumData extends Data
{
    public function __construct(
        public ?string $title,
        /** @var Collection<int, SongData> */ // <-- this gives a bit worse IDE support
        public Collection $songs,
    ) {}
}

// this now will cause the \Spatie\LaravelData\Exceptions\CannotCreateData exception, but only for "songs" property, "title" it still automatically sets to `null`
$albumData = AlbumData::from([]);

// and this works, but again sets "title" to null
$albumData = AlbumData::from(['songs' => []]);
dump($albumData->toArray()); // --> ["title" => null, "songs" => []]
```

**✅ Expected behavior**
- Promoted and class-level properties work the same on creation (if required and not passed - throws an exception).
- Nullable but not passed/set are not set to `null` automatically (unless a default value specifies that).

**🖥️ Versions**

Laravel: v10.22.0
Laravel Data: 4.1.0
PHP: 8.2.4

**Comment by rubenvanassche** [comment]
Hi @olexoliinyk0,

We try to mimic internals of PHP in laravel-data as best as possible. Creating a data object where the constructor promoted properties are provided and class defined properties aren't is a completely valid thing so we're going to keep that.

As for the nullable properties becoming null by default, yeah that's maybe a bit weird but it has been that since v1. I'll add it to my list for v5 to think about. For now you could overwrite the `DefaultValuesDataPipe` if you want an alternative behavior.

As for this:

```php
class AlbumData extends Data
{
    public function __construct(
        public ?string $title,
        /** @var Collection<int, SongData> */ // <-- this gives a bit worse IDE support
        public Collection $songs,
    ) {}
}
```

You canjust use a param annotation if you want, PHPStorm has support for this though.
