### ISSUE TITLE
throw Uncastable results in "Cannot throw objects that do not implement Throwable" from a custom Cast

### ISSUE THREAD

**Issue by olexoliinyk0** [spatie/laravel-data#685]
**✏️ Describe the bug**
Per [docs](https://spatie.be/docs/laravel-data/v4/getting-started/quickstart#content-local-casts) it says you need to `throw Uncastable::create();` to tell the package to try other casts, but the real result is that for PHP 8.2 it throws an `\Error` with the message `Cannot throw objects that do not implement Throwable`. Not to mention every static analysis tells me it's wrong. 

**↪️ To Reproduce**
Create a custom cast -> use it so that it definitely throws Uncastable. 

```php
use Spatie\LaravelData\Attributes\WithCast;
use Spatie\LaravelData\Casts\Cast;
use Spatie\LaravelData\Casts\Uncastable;
use Spatie\LaravelData\Data;
use Spatie\LaravelData\Support\Creation\CreationContext;
use Spatie\LaravelData\Support\DataProperty;

class StringCast implements Cast
{
    public function cast(DataProperty $property, mixed $value, array $properties, CreationContext $context): string
    {
        throw Uncastable::create();
        return 'anything';
    }
}

class PostData extends Data
{
    public function __construct(
        #[WithCast(StringCast::class)]
        public string $myString,
    ) {
    }
}

// here it throws the \Error
$postData = PostData::from([
    'myString' => 'hello',
]);
```

**✅ Expected behavior**
The Uncastable class to implement \Thorwable.

By the way how to achieve this "other casts" thing? I've tried to add another `#[WithCast(...)]` but it results in an \Error with message `Attribute "Spatie\LaravelData\Attributes\WithCast" must not be repeated`. 

**🖥️ Versions**

Laravel: v10.22.0
Laravel Data: 4.1.0
PHP: 8.2.4

**Comment by TomAdam** [comment]
This looks to be a documentation issue. If you look at the included casts they all return `Uncastable::create()` in this situation.

**Comment by olexoliinyk0** [comment]
@TomAdam thanks a lot! That was probably it. 

Maybe you also know how to provide multiple casts for the property as they mention in the "try other casts (if available)" part there?

**Comment by olexoliinyk0** [comment]
If someone else also wanders about "_try other casts (if available)_" part, so far I've only found out that if you return `Uncastable` from your local/custom Cast, it then will proceed with all the default casts (that are auto-found near the property definition). 

This means that if you have something like this (as in the initial message's example): 
```php
#[WithCast(StringCast::class)] 
public StringDto|string $myString,
```
and the `StringCast` returns `Uncastable`, it will behave as if that `WithCast` was never there -- will try to auto-cast it to `StringDto` (if an array is passed) or to `string` (if anything else is passed).
