### ISSUE TITLE
Can no longer use parse integer timestamp into Carbon object with Laravel 11

### ISSUE THREAD

**Issue by Sn0wCrack** [spatie/laravel-data#708]
**✏️ Describe the bug**
As of Carbon v3, they have introduced strict typing throughout the project, this has caused the `createFromFromat` function used by the DateTimeInterfaceCast class in this library to throw an error when it is provided an integer.

```
Carbon\CarbonImmutable::rawCreateFromFormat(): Argument #2 ($time) must be of type string, int given, called in /home/vagrant/atlas/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 647
```

I have an issue open with Carbon about this as well: https://github.com/briannesbitt/Carbon/issues/2967

As a workaround I wrote my owner caster specific to CarbonInterface objects that uses the `parse` function to interpret the timestamps instead and this seems to work fine.

**↪️ To Reproduce**
Provide us a pest test like this one which shows the problem:

```php

it('cannot parse a unix timestamp into a carbon object', function () {
    class DateDtoTest extends Data
    {
        public function __construct(
            public CarbonImmutable $date,
        ) {
        }
    }

    dd(DateDtoTest::from(['date' => 1710541965]));
});
```

Additionally you will need to add `U` as an accepted date time format to your configuration file.

**✅ Expected behavior**
Allow the parsing of an integer timestamp using the built in DateTimeInterfaceCast class.

**🖥️ Versions**

Laravel: 11.0.5
Laravel Data: 4.4.0
PHP: 8.3

**Comment by sebastiaanluca** [comment]
During upgrade, we encountered similar but it's trying to parse an object:

```
Carbon\CarbonImmutable::rawCreateFromFormat(): Argument #2 ($time) must be of type string, Illuminate\Support\Carbon given
```
