### ISSUE TITLE
Legacy docs search doesn't work.

### ISSUE THREAD

**Issue by Offlein** [spatie/laravel-data#716]
Since the release of spatie/laravel-data v4, the docs for v3 (and earlier, although I've never tested those) are unsearchable.

**To reproduce**
Go here: https://spatie.be/docs/laravel-data/v3/introduction

Search in the sidebar input on the left.

No results will ever be found.

**Comment by jonjakoblich** [comment]
Same issue experienced for me.

**Comment by rubenvanassche** [comment]
More of spatie.be issue since it is a problem for all out packages, told one of my colleagues who's working on this.

**Comment by Offlein** [comment]
@rubenvanassche Appreciate your forwarding it along. Just curious if there's any public place to track status of this! I'm sure it's not a major priority but we appreciate all you do. <3

**Comment by Offlein** [comment]
For what it's worth that issue was closed without reply with the advice to re-open it, but I do not have permissions.

This remains an issue.
