### ISSUE TITLE
Bug with typescript transformation of `Illuminate\Support\Collection` in v4.4.1

### ISSUE THREAD

**Issue by studnitz** [spatie/laravel-data#719]
I think this commit https://github.com/spatie/laravel-data/commit/66e2510aa031c0d0b132fe22db2fe0287cc3ca60 introduced a bug.

Example:

```php
<?php

use Spatie\LaravelData\Data;
use Illuminate\Support\Collection;


class FooData extends Data
{
   public function __construct(
        /** @var Collection<int, SomeData> */
        public Lazy|Collection $collection,
    ) {
    }
}
```

Before v.4.4.1 this would result in the Typescript Type:

```ts
declare namespace App.Data{
export type FooData = {
collection?: Array<App.Data.SomeData>;
};
};
```

Now it results in a record type something like this:

```ts
declare namespace App.Data{
export type FooData = {
collection?: Record<int, App.Data.SomeData>
};
};
```

which is not correct because it still gets serialized to an Array by Laravel-data in the end of the day.

This then leads to many wrongly caused type errors.

Also note that using `Collection<SomeData>` as the phpdoc type is not the solution imo, because then PHPStan errors that it expects two generic parameters `TKey` and `TValue`.

**Comment by studnitz** [comment]
> @studnitz 
> 
> 
> 
> Did you try with
> 
> 
> 
> ```php
> 
> /** @var Collection<SomeData> */
> 
> ```

Yes, but this results in a PHPStan error, see the last paragraph of the bug report.

**Comment by rubenvanassche** [comment]
Is a bug indeed, fixed in the next version.
