### ISSUE TITLE
Non nullable relation collections on models are not loaded

### ISSUE THREAD

**Issue by Tofandel** [spatie/laravel-data#729]
**✏️ Describe the bug**
When declaring a Data for a model with a non nullable and non lazy collection referencing a Relation, that relation is NOT included in the final data unless the relation was explicitely loaded on the model first (using `$model->load('relation_name')`)

**↪️ To Reproduce**
Provide us a pest test like this one which shows the problem:

```php

it('should load non nullable relations of model', function () {
    class ChapterData extends Data {
      public string $name;
    }

    class BaseData extends Data
    {
        public function __construct(
            /** @var Collection<int, ChapterData> */
            public Collection $chapters;
        ) {
        }
    }
    
    class Chapter extends Model {
    
    }
    class BaseModel extends Model {
        public function chapters() {
          return $this->hasMany(Chapter::class);
        }
    }

    $m => new BaseModel();
    dd(BaseData::from($m)->toArray()); // $m should be `['chapters' => []]` but it is `[]`
});
```

Attributes are present but present a huge performance issue, because calling `getMutatedAttributes` loads all of the available attributes of a model and not just the ones required in the DataClass, some getters can load relations and be really resource hungry but not be needed in a DataClass

Relevant code
https://github.com/spatie/laravel-data/blob/a5df67e06f1f9012261a9c14d007e81a8fd84046/src/Normalizers/ModelNormalizer.php#L32-L45

It seems a DataPipe to achieve this is required because normalizers are not passed the DataClass as a parameter (maybe they should in v5?)

**Comment by rubenvanassche** [comment]
Yeah this is a longer standing issue, we'll continue in the PR you've created.
