### ISSUE TITLE
Packages that require laravel-data throw `($throwWhenMaxDepthReached) must be of type bool, null given`

### ISSUE THREAD

**Issue by RhysLees** [spatie/laravel-data#731]
**✏️ Describe the bug**
Seems that in packages that require laravel-data, we have to set the following for tests to work.

```php
config()->set('data.throw_when_max_transformation_depth_reached', true);
```

Related to: #699 

> Comments in the related issue also experience this

**↪️ To Reproduce**

Create new package
Create dto
Try convert to array

```php
class BaseData extends Data
{
    public function __construct(
        public bool $something,
    ) {
    }
}


$data = BaseData::fromArray([
    'something' => false,
]);

$data->toArray(); // Error is thrown here
```

`Spatie\LaravelData\Support\Transformation\TransformationContext::__construct(): Argument #11 ($throwWhenMaxDepthReached) must be of type bool, null given, called in /***/vendor/spatie/laravel-data/src/Concerns/TransformableData.php on line 24`

**✅ Expected behavior**
DTO to be converted to Array successfully

**🖥️ Versions**

Laravel: 11
Laravel Data: 4.4.1
PHP: 8.3

**Comment by rubenvanassche** [comment]
Ensure you've got the data service provider running within your package:

```php
    protected function getPackageProviders($app)
    {
        return [
            LaravelPackagePlaygroundServiceProvider::class,
            LaravelDataServiceProvider::class
        ];
    }
```

**Comment by rubenvanassche** [comment]
We've got some new docs on this will be publishing later today.
