### ISSUE TITLE
Docs are out of date from this repo

### ISSUE THREAD

**Issue by hjanos1** [spatie/laravel-data#742]
**✏️ Describe the bug**
Docs site is not being updated with the latest changes to the docs files in this repo.

**↪️ To Reproduce**
Here is a [Wayback Machine snapshot](https://web.archive.org/web/20240408182026/https://spatie.be/docs/laravel-data/v4/as-a-data-transfer-object/creating-a-data-object) of one of the docs pages.

Even though #725 is merged and a new release has been created since that was merged, the docs still show the earlier way of creating a data object without magic methods.

**✅ Expected behavior**
Docs being updated with the latest changes to the docs files in this repo

**Comment by rubenvanassche** [comment]
Should be fixed normally with the new docs on Spatie.be, otherwise make an issue here: https://github.com/spatie/spatie.be.
