### ISSUE TITLE
Transforming to TypeScript  requested a package  Spatie\Enum

### ISSUE THREAD

**Issue by dmitriilopotovskii** [spatie/laravel-data#744]
```
php artisan typescript:transform
Class "Spatie\Enum\Enum" does not exist
```
The documentation doesn't say anything about installing it.
After installing spatie/enum  everything worked correctly

**🖥️ Versions**

Laravel: 11.3
Laravel Data: 4.5.0
PHP:8.2

**Comment by rubenvanassche** [comment]
Could you explain the exact steps you took to achieve this result? Normally data doesn't depend on spatie/enum.

**Comment by dmitriilopotovskii** [comment]
It's my mistake, I forgot to do this:
`Finally, add the Spatie\LaravelData\Support\TypeScriptTransformer\DataTypeScriptTransformer transformer to the transformers in the typescript-transformer.php config file.`
But the interesting thing is that after installing the spatie/enum package it also worked and it confused me

**Comment by nocttuam** [comment]
To resolve this error, I disabled the Spatie\TypeScriptTransformer\Transformers\SpatieEnumTransformer::class in the typescript-transformer.php config file.

**Comment by rubenvanassche** [comment]
Gonna close this, since it is a TS transformer problem and we also remove the Spatie enum transformer in v3 so should solve itself within a few weeks.
