### ISSUE TITLE
Can't include/exclude properties in collection since 4.5.0

### ISSUE THREAD

**Issue by ragulka** [spatie/laravel-data#746]
**✏️ Describe the bug**

When trying to include lazy properties in paginated data collections, the results do not include the lazy properties. 

Note: this issue occurs since 4.5.0 - the test below passes on 4.4.1

I suspect it might have something to do with changes in https://github.com/spatie/laravel-data/pull/696

**↪️ To Reproduce**
Provide us a pest test like this one which shows the problem:

```php

it('it cannot include lazy items through a paginated data collection', function () {
    $collection = new PaginatedDataCollection(
        MultiLazyData::class,
        new LengthAwarePaginator([
            DummyDto::rick(),
            DummyDto::bon(),
        ], 2, 15),
    );

    $filtered = $collection->through(fn (MultiLazyData $data) => $data->include('artist'))->toArray();

    expect($filtered['data'])->toMatchArray([
        ['artist' => 'Rick Astley'],
        ['artist' => 'Bon Jovi'],
    ]);
});
```

**✅ Expected behavior**
I would expect each item in the `$filtered['data']` array to include the `artist` key and value.

**🖥️ Versions**

Laravel: N/A
Laravel Data: 4.5.1
PHP: 8.2

**Comment by rubenvanassche** [comment]
Should be fixed with the next release!
