### ISSUE TITLE
Lazy properties are not countable since v4

### ISSUE THREAD

**Issue by linaspasv** [spatie/laravel-data#755]
**✏️ Describe the bug**
When trying to filter out empty lazy properties I get the following error:

``count(): Argument #1 ($value) must be of type Countable|array, Spatie\LaravelData\Support\Lazy\RelationalLazy given``

**↪️ To Reproduce**
```php

class CategoryData extends Data
{
    public function __construct(
        #[DataCollectionOf(ProductData::class)]
        public Lazy | array $products,
    ) {}

    public function includeProperties(): array
    {
        return [
            'products' => count($this->products) > 0,
        ];
    }

    public static function fromModel(Category $category): self
    {
        return new self(
            Lazy::whenLoaded('products', $category, fn () => ProductData::collect($category->products)),
        );
    }
}
```

**✅ Expected behavior**
I would expect this to work like described in the documentation:
https://spatie.be/docs/laravel-data/v4/as-a-resource/lazy-properties#content-conditionally

**🖥️ Versions**

Laravel: 10.33.0
Laravel Data: since 4.0.0
PHP: 8.2

**Comment by rubenvanassche** [comment]
You can do the following:

```php
public function includeProperties(): array
{
    return [
        'products' => count($this->products->resolve()) > 0,
    ];
}
```

I'll update the docs on this
