### ISSUE TITLE
validateAndCreate ignores rule from static rules method

### ISSUE THREAD

**Issue by speedball73** [spatie/laravel-data#756]
I have a custom Rule defined in the static rules method. While `validateAndCreate` seems to ignore the rules method `validate` works. So right now I am validating with `validate` and the creating with `from`. 

Is this a bug or intended?

Laravel: 10
Laravel Data: 4.4.0
PHP: 8.2

**Comment by rubenvanassche** [comment]
Please provide a test like asked in the issue template.
