### ISSUE TITLE
Dependencies fail to be injected into validation static override methods

### ISSUE THREAD

**Issue by kavihGB** [spatie/laravel-data#768]
**✏️ Describe the bug**
The `v3` and `v4` documentation are identical for the section titled `USING DEPENDENCIES IN OVERWRITTEN FUNCTIONALITY` under the validation. Specifically, the `ValidationContext` can be DI'd totally fine into the `rules()` static method override, but cannot in the `attributes()` static method override.

**Error:** `Unresolvable dependency resolving [Parameter #0 [ <required> mixed $payload ]] in class Spatie\LaravelData\Support\Validation\ValidationContext`

 In case it helps, I noticed the `Spatie\LaravelData\Resolvers\DataValidationRulesResolver` is passing the context into `rules()`, yet nothing is being passed into `attributes()` (in `Spatie\LaravelData\Resolvers\DataValidationMessagesAndAttributesResolver`). See below:

```php

// In `Spatie\LaravelData\Resolvers\DataValidationRulesResolver` around line 243
$overwrittenRules = app()->call([$class->name, 'rules'], ['context' => $validationContext]);
```

vs

```php

// In `Spatie\LaravelData\Resolvers\DataValidationMessagesAndAttributesResolver` around line 79
$attributes = collect(app()->call([$class, 'attributes']))
                ->keyBy(fn (mixed $messages, string $key) => $path->property($key)->get())
                ->merge($attributes)
                ->all();
```

**↪️ To Reproduce**
Add the following `attributes()` static method override to any DTO and attempt to run the validation. NOTE: the following code is copied directly from the `v4` documentation:

```php

    public static function attributes(
        ValidationAttributesLanguageRepository $validationAttributesLanguageRepository
    ): array
    {
        return [
            'title' => $validationAttributesLanguageRepository->get('title'),
            'artist' => $validationAttributesLanguageRepository->get('artist'),
        ];
    }
```

NOTE: In `v4` the `ValidationAttributesLanguageRepository` class does not exist, but that is not the problem because if you change the DI to `ValidationContext`, the error still persists.

**✅ Expected behavior**
Access to the DI'd object/value.

**🖥️ Versions**

Laravel: 11.5.0
Laravel Data: 4.5.1
PHP: 8.3.6

**Comment by rubenvanassche** [comment]
I don't really see this as an issue, the docs specify that DI is possible in the attributes method not that a ValidationContext can be injected that's only reserved for the rules method. As for `ValidationAttributesLanguageRepository` it is just an example of something that can be injected, it does not exist in any data version.

I think a feature like this can be added quite easily, so I always welcome PR's adding this but at the moment I'm going to close the issue since we do not advertise such a feature in the docs.
