### ISSUE TITLE
#[GreaterThan], #[GreaterThanOrEqualTo], #[LessThan], #[LessThanOrEqualTo] works not as expected (size comparision)

### ISSUE THREAD

**Issue by isag-clemensbastian** [spatie/laravel-data#772]
**✏️ Describe the bug**
Usage of the validation Attributes 

- #[GreaterThan]
- #[GreaterThanOrEqualTo]
- #[LessThan]
- #[LessThanOrEqualTo]

is not fully compatible with the laravel implemetation of the corresponding validation rules. While the laravel documentation allows a `field` **or** a `comparison value` to be passed, the implementation in laravel-data always tries to evaluate the given value as a field reference.

> https://laravel.com/docs/11.x/validation#rule-gt
> The field under validation must be greater than the given field or value. The two fields must be of the same type. Strings, numerics, arrays, and files are evaluated using the same conventions as the [size](https://laravel.com/docs/10.x/validation#rule-size) rule.

The constructor method of those validation rules looks like:

```php
// Spatie\LaravelData\Attributes\Validation\LessThan
public function __construct(
        string|FieldReference $field,
    ) {
        $this->field = $this->parseFieldReference($field);
    }
```

**✅ Expected behavior**
When a string is passed to the constructor it is evaluated as a comparision value instead of a field reference.

**🖥️ Versions**

Laravel: 10+
Laravel Data: 4
PHP: 8

**Comment by rubenvanassche** [comment]
Will be fixed in the next release, but not sure if Laravel's implementation is completely correct:

```php
    dd(Validator::make([
        'a' => 'test',
        'b' => 42,
        'c' => 3.14,
        'd' => ['a', 'b', 'c'],
    ], [
            'a' => 'string|gte:2',
            'b' => 'numeric|gte:2',
            'c' => 'numeric|gte:2',
            'd' => 'array|gte:2',
        ]
    )->errors());
```

Provides:

```php
Illuminate\Support\MessageBag {#1007
  #messages: array:2 [
    "a" => array:1 [
      0 => "The a field must be greater than or equal to 2 characters."
    ]
    "d" => array:1 [
      0 => "The d field must have 2 items or more."
    ]
  ]
  #format: ":message"
}
```

**Comment by isag-clemensbastian** [comment]
@rubenvanassche you're right. I can reproduce the same behaviour in laravel as you pointed out. Pretty interesting and I'm pretty sure it's a bug in the framework. Will look further into it and open a bug report in laravel-framework.
