### ISSUE TITLE
Backward compatibility is broken 4.5.1 🡒 4.6.0

### ISSUE THREAD

**Issue by alexrififi** [spatie/laravel-data#774]
**✏️ Describe the bug**
The same thing happened as described in this issue #590 

**✅ Expected behavior**
If the value of the data property can be `null` and model attribute is in fact `null`, then the value of the data property must also be `null`

**🖥️ Versions**

Laravel: 10.48.10
Laravel Data: 4.6.0
PHP: 8.3

**Comment by rubenvanassche** [comment]
Will be fixed with the next version
