### ISSUE TITLE
Dot notation doesn't work with related model's property with MapInputName

### ISSUE THREAD

**Issue by marielsabornido** [spatie/laravel-data#783]
**✏️ Describe the bug**
With the new model normalizer class, "dot" notation doesn't work with relation property anymore. I'm not sure if this was intended to be removed in v4.6.

**↪️ To Reproduce**

```php

class PostData extends Data
{
    public function __construct(
        #[MapInputName('user.name')]
        public string $author,
    ) {
    }
}

$post = PostData::from(Post::with('user')->find(1));
// throws "Could not create `App\\Data\\PostData`: the constructor requires 1 parameter, 0 given. Parameters missing: name.",

```

**✅ Expected behavior**
It should be able to get the `name` property of the related `User`. This provided us an easy way to flatten related property.

**🖥️ Versions**
Laravel: 11.9.2
Laravel Data: 4.6
PHP: 8.2

**Comment by nesh-ua** [comment]
I have the same problem. 
When you don't add property user to your data object, you can't use nesting properties.

This code is working:

```
class PostData extends Data
{
    public function __construct(
        public User $user,
        #[MapInputName('user.name')]
        public string $author,
    ) {
    }
}

```

I think there is issue here.

**Comment by rubenvanassche** [comment]
Hi All,

This was actually never a feature, cool that it worked but we rewrote the ModelNormalizer a few weeks ago to make it more performant which stopped the feature from working. If someone wants to add it as a feature to the new NormalizedModel class, I would certainly accept a PR but for now I'm not going to implement this myself.

As a solution you could write a magic creation method to solve this issue quickly.
