### ISSUE TITLE
Eager loaded relations are reset which throws a lazy loading violation 

### ISSUE THREAD

**Issue by sebastiaanluca** [spatie/laravel-data#792]
**✏️ Describe the bug**
A change in https://github.com/spatie/laravel-data/pull/773/files#diff-5a676e204bcb067cd1bf62ef73416609c339f8e16479ab7b38021e9799c2d607R29 throws an exception if you:
- use `Model::preventLazyLoading();` or full strict mode
- have an attribute getter that uses a relation
- the relation is eager loaded using `with()`
- you append the attribute
- create a data object from it

Works fine if it it's just `$this->properties = $model->toArray();` like before.

In our app for instance, this doesn't work anymore (simplified):

```php
$objects = $user->objects->append('accessor_using_relation');

DataObject::collect($objects, DataCollection::class),
```

But this now does, without the append:

```php
DataObject::collect($user->objects, DataCollection::class),
```

Granted it's shorter and more convenient, but it's a breaking change nonetheless and sometimes we do need to append stuff (or it was appended before).

**↪️ To Reproduce**
I've been trying to reproduce it in a Pest test so I could file a valid bug, but `Model::preventLazyLoading();` doesn't seem to work so the exception isn't triggered.

```php
<?php

use Illuminate\Database\Eloquent\Model;
use Spatie\LaravelData\Tests\Fakes\FakeModelData;
use Spatie\LaravelData\Tests\Fakes\Models\FakeModel;
use Spatie\LaravelData\Tests\Fakes\Models\FakeNestedModel;

it('can get a data object from a model with accessors that use relations', function () {
    // FIXME: doesn't seem to take effect
    Model::preventLazyLoading();

    $model = FakeModel::factory()->create();
    FakeNestedModel::factory()->for($model)->create();

    $freshModel = FakeModel::query()
        ->with('fakeNestedModels')
        ->first()
        ->append('accessorUsingRelation');

    $data = FakeModelData::from($freshModel);

    expect($freshModel)
        ->accessor_using_relation
        ->toEqual($data->accessor_using_relation);
});

<?php

namespace Spatie\LaravelData\Tests\Fakes;

use Spatie\LaravelData\Data;

class FakeModelData extends Data
{
    public function __construct(public string $accessor_using_relation) {}
}

// Add in FakeModel
public function getAccessorUsingRelationAttribute(): string
{
    return $this->fakeNestedModels->first()->string;
}
```

**✅ Expected behavior**
It doesn't throw a lazy loading violation exception and uses the relation in the attribute getter, even when appended.

**🖥️ Versions**

Laravel:11.10.0
Laravel Data: 4.7.0
PHP: 8.3.7

**Comment by rubenvanassche** [comment]
I think I found a solution, problem is that Eloquent is a strange beast sometimes.
