### ISSUE TITLE
#[List] validation attribute not working - syntax error, unexpected token "list"

### ISSUE THREAD

**Issue by atang08** [spatie/laravel-data#806]
I think you guys need to update the docs about the List validation attribute.

I tried using it for my current project and I was getting a syntax error, unexpected token 'list'.

I then took a peak at the code source and it looks like it should be changed to:

`use Spatie\LaravelData\Attributes\Validation\ListType;

        #[ListType]
        public array $disabled_list = [],`

Not really a bug, but thought I'd share in case anyone else runs in to this issue.

**Comment by rubenvanassche** [comment]
Done
