### ISSUE TITLE
Lazy::whenLoaded has not any method that indicate is relation loaded or not?

### ISSUE THREAD

**Issue by MjavadBakhshi** [spatie/laravel-data#827]
**✏️ Describe the bug**
Lazy::whenLoaded has not any method that indicate is relation loaded or not?

In addition at Spatie\LaravelData\Support\Lazy\RelationLazy  in resolve method :
     `php`
   return $this->model->{$this->relation} !== null ? ($this->value)() : null;
   $this->model->{$this->relation} cause load the model relation i think you must change it to $this->model->relationLoaded($this->relation) ?  ($this->value)() : null;

**✅ Expected behavior**
I expected have any method which returns boolean for checking is a field with Lazy type load the defined relation or not for example
if i declare public readonly Lazy|TaskData  $task   and in
 fromModel method:
self::fron([
   .....,
            'task' => Lazy::whenLoaded('task', $userTask, fn() => $userTask->task->getData())
]);  

i want to findout load status of relation like this :
if($userTaskData->task->isLoaded()) do something

**🖥️ Versions**

Laravel: 11.9
Laravel Data: 4
PHP: 8.2

**Comment by rubenvanassche** [comment]
Lazy properties are only useful in outputting a data object as an array, response, json, ... so normally you wouldn't call any method on it. You can use the `shouldBeIncluded` method since that's basically what data does.
