### ISSUE TITLE
If extends is Dto, not Data, DataVarDumperCaster error occurs

### ISSUE THREAD

**Issue by jskorlol** [spatie/laravel-data#833]
**✏️ Describe the bug**
If extends is Dto and not Data, a DataVarDumperCaster error occurs.

The contents cannot be checked with dump or dd.

**↪️ To Reproduce**

```php

    class BaseData extends Dto
    {
        public function __construct(
            public int $age,
        ) {
        }
    }

   $BaseData = new BaseData(age: 1);
   dd($BaseData);
```

**✅ Expected behavior**
```
Spatie\LaravelData\Support\VarDumper\DataVarDumperCaster::castDataObject(): Argument #1 ($data) must be of type Spatie\LaravelData\Contracts\TransformableData, App\Services\Transaction\Data\TransactionData given, called in /var/www/vendor/symfony/var-dumper/Cloner/AbstractCloner.php on line 370
```

**🖥️ Versions**

Laravel: 11
Laravel Data: 4.7.2
PHP: 8.3

**Comment by rust17** [comment]
Hi @jskorlol. To help us better understand the problem, could you please provide more details? Specifically, it would be helpful to know:
1. The exact steps to reproduce the issue.
2. The expected behavior versus the actual behavior.

**Comment by rubenvanassche** [comment]
This should be fixed with the next version.
