### ISSUE TITLE
Possible break in 4.8.0

### ISSUE THREAD

**Issue by bastianschwarz** [spatie/laravel-data#839]
**✏️ Describe the bug**
Hey there, jsut as a heads up: Dependabot already picked up the 4.8.0 release and our CI lit up like a christmas tree.

![image](https://github.com/user-attachments/assets/1faf693c-ca81-4fbb-8d0e-37d3d1920593)

**↪️ To Reproduce**
I haven't done any digging yet, thought it would be more important to maybe get a warning out fast. :)

**✅ Expected behavior**
Since this is a minor release it should not break existing installations.

**🖥️ Versions**

Laravel: 10
Laravel Data: 4.8.0
PHP: 8.3

**Comment by rubenvanassche** [comment]
Apparently a dependency was included in the dev dependencies but not in the non dev dependencies, fixed with 4.8.1
