### ISSUE TITLE
TransformableData extends ContextableData interface

### ISSUE THREAD

**Issue by adriaanzon** [spatie/laravel-data#861]
**✏️ Describe the bug**

In commit 1732519693ac738cbc9cb21fdd00446c7a6a46e6, the [ContextableData trait][] was removed from the [TransformableData trait][]. However, the [TransformableData interface] still implements the [ContextableData interface][].

[ContextableData trait]: https://github.com/spatie/laravel-data/blob/main/src/Concerns/ContextableData.php
[TransformableData trait]: https://github.com/spatie/laravel-data/blob/main/src/Concerns/TransformableData.php
[TransformableData interface]: https://github.com/spatie/laravel-data/blob/main/src/Contracts/TransformableData.php
[ContextableData interface]: https://github.com/spatie/laravel-data/blob/main/src/Contracts/ContextableData.php

In one of our DTO's, we extend directly from `Spatie\LaravelData\Dto` and implement `TransformableData`. When trying to update laravel-data to its latest version, our test suite fails because we're not implementing all methods on the `TransformableData` interface anymore:

```
PHP Fatal error:  Class [Our DTO class...] contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Spatie\LaravelData\Contracts\ContextableData::getDataContext)
```

And PHPStan fails too:

```
Non-abstract class [Our DTO class...] contains abstract method getDataContext() from interface Spatie\LaravelData\Contracts\ContextableData.
```

**↪️ To Reproduce**

```php
test('TransformableData trait implements TransformableData interface', function () {
    $dto = new class () extends Dto implements \Spatie\LaravelData\Contracts\TransformableData {
        use \Spatie\LaravelData\Concerns\TransformableData;
    };

    expect($dto)->not->toBeInstanceOf(\Spatie\LaravelData\Contracts\ContextableData::class);
});
```

**✅ Expected behavior**

Adding the `TransformableData` trait to a DTO should implement all methods on the `TransformableData` interface. I think the `ContextableData` interface can be removed from `TransformableData`.

**🖥️ Versions**

Laravel: 11.22.0
Laravel Data: 4.8.2
PHP: 8.3.11

**Comment by rubenvanassche** [comment]
That's not good 4.9.0 should fix this.
