### ISSUE TITLE
Include/exclude does not work on the `Resource` class 

### ISSUE THREAD

**Issue by Tofandel** [spatie/laravel-data#868]
**✏️ Describe the bug**
Using `include('someProp')` or `exclude` on a DataClass that extends the `Resource` class does not work because `Resource` is missing the `ContextableDataContract` but has the trait

This means that this condition 
https://github.com/spatie/laravel-data/blob/cf86d7abc18437a68d34c50072e5951b4a0bcf98/src/Concerns/TransformableData.php#L35-L37

Cannot pass and the transformationContext does not contain any partials

Here is a pest case that demonstrates the issue
```php
it('can work with lazy laravel data collections', function () {
    $dataClass = new class () extends Resource {
        #[DataCollectionOf(SimpleData::class)]
        public Lazy|Collection $lazyCollection;
    };

    $dataClass->lazyCollection = Lazy::create(fn () => collect([
        SimpleData::from('A'),
        SimpleData::from('B'),
    ]));

    expect($dataClass->toArray())->toMatchArray([]);

    expect($dataClass->include('lazyCollection')->toArray())->toMatchArray([
        'lazyCollection' => [
            ['string' => 'A'],
            ['string' => 'B'],
        ],
    ]);
});
```

**Comment by SethSharp** [comment]
I think adding `ContextableData` to the base `Resource` class might be opinionated to your use case. I ran into the same situation but came across this section of the docs - [Traits and Interfaces](https://spatie.be/docs/laravel-data/v4/advanced-usage/traits-and-interfaces). Which suggests that `Resource` is a generic implementation - this package is designed to allow us to add our own functionality where necessary.

**Comment by Tofandel** [comment]
I really don't think so because the trait to allow include and exclude Is used on it, if that was the case, the trait should not be on it, and the doc suggests using it as an alternative to Data that doesn't have data validation and thus performs a bit better

https://spatie.be/docs/laravel-data/v4/as-a-resource/from-data-to-resource

**Comment by SethSharp** [comment]
hmm yes I see your point now. I was mixing up Resource and Dto.

**Comment by rubenvanassche** [comment]
I've added it to Resource, IncludeableData earlier extended ContextableData but that gave circular dependency problems when trying to analyze data for TypeScript Transformer 3. This should fix the issue.
