### ISSUE TITLE
Optimize exception when app/Data doesn't exist

### ISSUE THREAD

**Issue by JasperTey** [spatie/laravel-data#892]
**✏️ Describe the bug**
Optimize command `data:cache-structures` fails if app/Data directory doesn't exist.

This issue surfaced as a result of the recent registration of optimize commands introduced in #880, while running `php artisan optimize` in production. The app in question does not store data objects inside app/Data and therefore the folder didn't exist.

**↪️ To Reproduce**
- Remove app/Data folder, or temporarily rename it.
- run `php artisan data:cache-structures` or `php artisan optimize` if on Laravel 11.27+.
- `Symfony\Component\Finder\Exception\DirectoryNotFoundException` will be thrown expecting app/Data to exist.

**✅ Expected behavior**
Gracefully continue if app/Data doesn't exist.

**🖥️ Versions**

Laravel: 11.29.0
Laravel Data: 4.11.0
PHP: 8.3.12

**Comment by JasperTey** [comment]
Reporting this issue for the record, I will try to work on a PR later when I have some time - or if anyone else can get to it sooner, that's great too.

**Comment by davideprevosto** [comment]
I have the same problem as you. We are using a very basic custom structure folder:

![Image](https://github.com/user-attachments/assets/0bd86fb8-facd-4ef6-9fb7-b2dc9e1369ff)

Unfortunately using the version `v4.11.0` and running `php artisan optimize` we are getting:

```shell
   INFO  Caching framework bootstrap, configuration, and metadata.

  config ................................................................. 74.53ms DONE
  events .................................................................. 4.21ms DONE
  routes ................................................................ 174.12ms DONE
  views ................................................................. 441.81ms DONE
  laravel-data ............................................................ 8.42ms FAIL

   Symfony\Component\Finder\Exception\DirectoryNotFoundException

  The "src/App/Data" directory does not exist.

  at vendor/symfony/finder/Finder.php:646
    642▕             } elseif ($glob = glob($dir, (\defined('GLOB_BRACE') ? \GLOB_BRACE : 0) | \GLOB_ONLYDIR | \GLOB_NOSORT)) {
    643▕                 sort($glob);
    644▕                 $resolvedDirs[] = array_map($this->normalizeDir(...), $glob);
    645▕             } else {
  ➜ 646▕                 throw new DirectoryNotFoundException(sprintf('The "%s" directory does not exist.', $dir));
    647▕             }
    648▕         }
    649▕
    650▕         $this->dirs = array_merge($this->dirs, ...$resolvedDirs);

      +33 vendor frames

```

**Comment by rubenvanassche** [comment]
Yeah, fixed this.
