### ISSUE TITLE
No matching handler found for Mockery_0_Illuminate_Config_Repository::get('data.max_transformation_depth', NULL)

### ISSUE THREAD

**Issue by quangiahopan** [spatie/laravel-data#906]
**✏️ Describe the bug**
Unit tests failed whenever transform is executed

**↪️ To Reproduce**
Create a new `ChildData` object derived from `Spatie\LaravelData\Data`

```php

use Illuminate\Support\Facades\Validator;

it('cann validate data', function () {
    class AppointmentDTO extends Data
    {
        public function __construct(
            public readonly int $externalId,
            public readonly string $name,
        ) {
            $this->validateData();
        }
        protected function validateData(): void
        {
            $validator = Validator::make($this->toArray(), $this->getRules());
            $validator->validate();
        }
    }


    dd((new AppointmentDTO(1, 'Test object'))->validateData());
});
```

**✅ Expected behavior**
Unit tests failed when upgrading to version 4.2.0

**🖥️ Versions**

Laravel: 10.0
Laravel Data: 4.2
PHP: 8.3

**Comment by rust17** [comment]
Hi @quangiahopan ,

I'm unable to reproduce your test scenario because the `getRules` method isn't available. Could you please provide more details about your test case and any error messages you're encountering? This will help me understand the issue and provide assistance.

**Comment by quangiahopan** [comment]
I couldn't reproduce it now. So I'll closed this thread. Thank you for your help!
